import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.OP01,
    setNumber: 1,
    cardName: 'Roronoa Zoro',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!!x1] [Your Turn] All of your Characters gain +1000 power.`,
    life: 5,
  },{
    setId: SetId.OP01,
    setNumber: 2,
    cardName: 'Trafalgar Law',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED, CardColor.GREEN ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HeartPirates ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] ➁ (You may rest the specified number of DON!! cards in your cost area.): If you have 5 Characters, return 1 of your Characters to your hand. Then, play up to 1 Character with a cost of 5 or less from your hand that is a different color than the returned Character.`,
    life: 4,
  },{
    setId: SetId.OP01,
    setNumber: 3,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED, CardColor.GREEN ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] [Once Per Turn] ➃ (You may rest the specified number of DON!! cards in your cost area.): Set up to 1 of your {Supernovas} or {Straw Hat Crew} type Character cards with a cost of 5 or less as active. It gains +1000 power during this turn.`,
    life: 4,
  },{
    setId: SetId.OP01,
    setNumber: 4,
    cardName: 'Usopp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.RANGED,
    counter: 2000,
    effectText: `[DON!! x1] [Your Turn] [Once Per Turn] Draw 1 card when your opponent activates an Event.`,
  },{
    setId: SetId.OP01,
    setNumber: 5,
    cardName: 'Uta',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.FILM ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Add up to 1 red Character card other than [Uta] with a cost of 3 or less from your trash to your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 6,
    cardName: 'Otama',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hagane Tsurugi' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.SPECIAL,
    counter: 2000,
    effectText: `[On Play] Give up to 1 of your opponent's Characters -2000 power during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 7,
    cardName: 'Caribou',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.CaribouPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On K.O.] K.O. up to 1 of your opponent's Characters with 4000 power or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 8,
    cardName: 'Cavendish',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'BISAI', 'BISAI' ],
    imgObjs: [ '_dummy.png', 'p_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.BeautifulPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] You may add 1 card from your Life area to your hand: This Character gains [Rush] during this turn. (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP01,
    setNumber: 9,
    cardName: 'Carrot',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Rina Usui' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Minks ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP01,
    setNumber: 10,
    cardName: 'Komachiyo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.LandOfWano ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 11,
    cardName: 'Gordon',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.FILM ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[On Play] You may place 1 card from your hand at the bottom of your deck: Draw 1 card.`,
  },{
    setId: SetId.OP01,
    setNumber: 12,
    cardName: 'Sai',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.HapposuiArmy ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 13,
    cardName: 'Sanji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'NIJIMAARC' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[Activate: Main] [Once Per Turn] You may add 1 card from your Life area to your hand: This Character gains +2000 power during this turn. Then, give this Character up to 2 rested DON!! cards.`,
  },{
    setId: SetId.OP01,
    setNumber: 14,
    cardName: 'Jinbe',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.StrawHatCrew ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [DON!! x1] [On Block] Play up to 1 red Character card with a cost of 2 or less from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 15,
    cardName: 'Tony Tony.Chopper',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `[DON!! x1] [When Attacking] You may trash 1 card from your hand: Add up to 1 {Straw Hat Crew} type Character card other than [Tony Tony.Chopper] with a cost of 4 or less from your trash to your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 16,
    cardName: 'Nami',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Sunohara' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Straw Hat Crew} type Character card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP01,
    setNumber: 17,
    cardName: 'Nico Robin',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[DON!! x1] [When Attacking] K.O. up to 1 of your opponent's Characters with 3000 power or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 18,
    cardName: 'Hajrudin',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Giant, TypeTags.NewGiantPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 19,
    cardName: 'Bartolomeo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'BISAI' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.BartoClub ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [DON!! x2] [Opponent's Turn] This Character gains +3000 power.`,
  },{
    setId: SetId.OP01,
    setNumber: 20,
    cardName: 'Hyogoro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Activate: Main] You may rest this Character: Up to 1 of your Leader or Character cards gains +2000 power during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 21,
    cardName: 'Franky',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.RANGED,
    effectText: `[DON!! x1] This Character can also attack your opponent's active Characters.`,
  },{
    setId: SetId.OP01,
    setNumber: 22,
    cardName: 'Brook',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [When Attacking] Give up to 2 of your opponent's Characters -2000 power during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 23,
    cardName: 'Marco',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.FormerWhitebeardPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 24,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'K Akagishi' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[DON!! x2] This Character cannot be K.O.'d in battle by <Strike> attribute Characters.
    [Activate: Main] [Once Per Turn] Give this Character up to 2 rested DON!! cards.`,
  },{
    setId: SetId.OP01,
    setNumber: 25,
    cardName: 'Roronoa Zoro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'AKIRA EGAWA' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Rush] (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP01,
    setNumber: 26,
    cardName: 'Gum-Gum Fire-Fist Pistol Red Hawk',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, K.O. up to 1 of your opponent's Characters with 4000 power or less.`,
    triggerText: `[Trigger] Give up to 1 of your opponent's Leader or Character cards -10000 power during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 27,
    cardName: 'Round Table',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.BeautifulPirates ],
    cost: 4,
    effectText: `[Main] Give up to 1 of your opponent's Characters -10000 power during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 28,
    cardName: 'Green Star Rafflesia',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Counter] Give up to 1 of your opponent's Leader or Character cards -2000 power during this turn.`,
    triggerText: `[Trigger] Activate this card's [Counter] effect.`,
  },{
    setId: SetId.OP01,
    setNumber: 29,
    cardName: 'Radical Beam!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 2 or less Life cards, that card gains an additional +2000 power.`,
    triggerText: `[Trigger] Up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 30,
    cardName: 'In Two Years!! At the Sabaody Archipelago!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Main] Look at 5 cards from the top of your deck; reveal up to 1 {Straw Hat Crew} type Character card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP01,
    setNumber: 31,
    cardName: 'Kouzuki Oden',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] You can trash 1 {Land of Wano} type card from your hand: Set up to 2 of your DON!! cards as active.`,
    life: 5,
  },{
    setId: SetId.OP01,
    setNumber: 32,
    cardName: 'Ashura Doji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] If your opponent has 2 or more rested Characters, this Character gains +2000 power.`,
  },{
    setId: SetId.OP01,
    setNumber: 33,
    cardName: 'Izo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.FormerWhitebeardPirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.RANGED,
    counter: 2000,
    effectText: `[On Play] Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 34,
    cardName: 'Inuarashi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'TAPIOCA', 'TAPIOCA' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Minks, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x2] [When Attacking] Set up to 1 of your DON!! cards as active.`,
  },{
    setId: SetId.OP01,
    setNumber: 35,
    cardName: 'Okiku',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] [Once Per Turn] Rest up to 1 of your opponent's Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 36,
    cardName: 'Otsuru',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 37,
    cardName: 'Kawamatsu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP01,
    setNumber: 38,
    cardName: 'Kanjuro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [When Attacking] K.O. up to 1 of your opponent's rested Characters with a cost of 2 or less.
    [On K.O.] Your opponent chooses 1 card from your hand; trash that card.`,
  },{
    setId: SetId.OP01,
    setNumber: 39,
    cardName: 'Killer',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Koushi Rokushiro' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [DON!! x1] [On Block] If you have 3 or more Characters, draw 1 card.`,
  },{
    setId: SetId.OP01,
    setNumber: 40,
    cardName: `Kin'emon`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'touge369' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 6,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If your Leader is [Kouzuki Oden], play up to 1 {The Akazaya Nine} type Character card with a cost of 3 or less from your hand.
    [DON!! x1] [When Attacking] [Once Per Turn] Set up to 1 of your {The Akazaya Nine} type Character cards with a cost of 3 or less as active.`,
  },{
    setId: SetId.OP01,
    setNumber: 41,
    cardName: 'Kouzuki Momonosuke',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area) You may rest this Character: Look at 5 cards from the top of your deck; reveal up to 1 {Land of Wano} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP01,
    setNumber: 42,
    cardName: 'Komurasaki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `[On Play] ③ (You may rest the specified number of DON!! cards in your cost area.): If your Leader is [Kouzuki Oden], set up to 1 of your {Land of Wano} type Character cards with a cost of 3 or less as active.`,
  },{
    setId: SetId.OP01,
    setNumber: 43,
    cardName: 'Shinobu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 44,
    cardName: 'Shachi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.HeartPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] If you don't have [Penguin], play up to 1 [Penguin] from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 45,
    cardName: 'Jean Bart',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.HeartPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 46,
    cardName: 'Denjiro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] If your Leader is [Kouzuki Oden], set up to 2 of your DON!! cards as active.`,
  },{
    setId: SetId.OP01,
    setNumber: 47,
    cardName: 'Trafalgar Law',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Makitoshi' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HeartPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] You may return 1 Character to your hand: Play up to 1 Character card with a cost of 3 or less from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 48,
    cardName: 'Nekomamushi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'TAPIOCA', 'TAPIOCA' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Minks, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Rest up to 1 of your opponent's Characters with a cost of 3 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 49,
    cardName: 'Bepo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'TAPIOCA' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Minks, TypeTags.HeartPirates ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] Play up to 1 {Heart Pirates} type card other than [Bepo] with a cost of 4 or less from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 50,
    cardName: 'Penguin',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.HeartPirates ],
    cost: 3,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] If you don't have [Shachi], play up to 1 [Shachi] from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 51,
    cardName: 'Eustass"Captain"Kid',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'Anime', 'Makitoshi', 'WANTED' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] [Opponent's Turn] If this Character is rested, your opponent cannot attack any card other than the Character [Eustass"Captain"Kid].
    [Activate: Main] [Once Per Turn] You may rest this Character: Play up to 1 Character card with a cost of 3 or less from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 52,
    cardName: 'Raizo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[When Attacking] [Once Per Turn] If you have 2 or more rested Characters, draw 1 card.`,
  },{
    setId: SetId.OP01,
    setNumber: 53,
    cardName: 'Wire',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Koushi Rokushiro' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.KidPirates ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 54,
    cardName: 'X.Drake',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'BISAI' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.Navy, TypeTags.DrakePirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 55,
    cardName: 'You Can Be My Samurai!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    effectText: `[Main] You may rest 2 of your Characters: Draw 2 cards.`,
  },{
    setId: SetId.OP01,
    setNumber: 56,
    cardName: 'Demon Face',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HawkinsPirates ],
    cost: 6,
    effectText: `[Main] K.O. up to 2 of your opponent's rested Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 57,
    cardName: 'Paradise Waterfall',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, set up to 1 of your Characters as active.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 58,
    cardName: 'Punk Gibson',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Characters.`,
  },{
    setId: SetId.OP01,
    setNumber: 59,
    cardName: 'BE-BENG!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 3,
    effectText: `[Main] You may trash 1 {Land of Wano} type card from your hand: Set up to 1 of your {Land of Wano} type Character cards with a cost of 3 or less as active.`,
  },{
    setId: SetId.OP01,
    setNumber: 60,
    cardName: 'Donquixote Doflamingo',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x2] [When Attacking] ➀ (You may rest the specified number of DON!! cards in your cost area.): Reveal 1 card from the top of your deck. If that card is a {The Seven Warlords of the Sea} type Character card with a cost of 4 or less, you may play that card rested.`,
    life: 5,
  },{
    setId: SetId.OP01,
    setNumber: 61,
    cardName: 'Kaido',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE, CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [Your Turn] [Once Per Turn] When your opponent's Character is K.O.'d, add up to 1 DON!! card from your DON!! deck and set it as active.`,
    life: 4,
  },{
    setId: SetId.OP01,
    setNumber: 62,
    cardName: 'Crocodile',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE, CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] When you activate an Event, you may draw 1 card if you have 4 or less cards in your hand and haven't drawn a card using this Leader's effect during this turn.`,
    life: 4,
  },{
    setId: SetId.OP01,
    setNumber: 63,
    cardName: 'Arlong',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anderson' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.ArlongPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [Activate: Main] You may rest this Character: Choose 1 card from your opponent's hand; your opponent reveals that card. If the revealed card is an Event, place up to 1 card from your opponent's Life area at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP01,
    setNumber: 64,
    cardName: 'Alvida',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'Hashimoto Q', 'Hashimoto Q' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.BuggyPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] You may trash 1 card from your hand: Return up to 1 of your opponent's Characters with a cost of 3 or less to the owner's hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 65,
    cardName: 'Vergo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Navy, TypeTags.DonquixotePirates, TypeTags.PunkHazard ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 66,
    cardName: 'Krieg',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anderson' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.KriegPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 67,
    cardName: 'Crocodile',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'tatsuya' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Banish] (When this card deals damage, the target card is trashed without activating its Trigger.)
    [DON!! x1] Give blue Events in your hand -1 cost.`,
  },{
    setId: SetId.OP01,
    setNumber: 68,
    cardName: 'Gecko Moria',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'phima' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Your Turn] This Character gains [Double Attack] if you have 5 or more cards in your hand.
    (This card deals 2 damage.)`,
  },{
    setId: SetId.OP01,
    setNumber: 69,
    cardName: 'Caesar Clown',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Moopic' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Scientist, TypeTags.PunkHazard ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On K.O.] Play up to 1 [Smiley] from your deck, then shuffle your deck.`,
  },{
    setId: SetId.OP01,
    setNumber: 70,
    cardName: 'Dracule Mihawk',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Nijihayashi', 'AKIRA EGAWA' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea ],
    cost: 9,
    power: 9000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Place up to 1 Character with a cost of 7 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP01,
    setNumber: 71,
    cardName: 'Jinbe',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'BISAI' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.StrawHatCrew ],
    cost: 4,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Place up to 1 Character with a cost of 3 or less at the bottom of the owner's deck.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP01,
    setNumber: 72,
    cardName: 'Smiley',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.BiologicalWeapon, TypeTags.PunkHazard ],
    cost: 3,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[DON!! x1] [Your Turn] This Character gains +1000 power for every card in your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 73,
    cardName: 'Donquixote Doflamingo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Suemi jun', 'Hayaken-sarena' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of the deck in any order.`,
  },{
    setId: SetId.OP01,
    setNumber: 74,
    cardName: 'Bartholomew Kuma',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Moopic' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.RevolutionaryArmy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] Play up to 1 [Pacifista] with a cost of 4 or less from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 75,
    cardName: 'Pacifista',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.BiologicalWeapon, TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `Under the rules of this game, you may have any number of this card in your deck.
    [Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP01,
    setNumber: 76,
    cardName: 'Bellamy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 77,
    cardName: 'Perona',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'Ryuda', 'Ryuda' ],
    imgObjs: [ '_dummy.png', 'p_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of the deck in any order.`,
  },{
    setId: SetId.OP01,
    setNumber: 78,
    cardName: 'Boa Hancock',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Mutsumi Sasaki', 'Hashimoto Q' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.KujaPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [DON!! x1] [When Attacking]/[On Block] Draw 1 card if you have 5 or less cards in your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 79,
    cardName: 'Ms. All Sunday',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Mutsumi Sasaki' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 3,
    power: 1000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] If your Leader has the {Baroque Works} type, add up to 1 Event from your trash to your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 80,
    cardName: 'Miss Doublefinger(Zala)',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On K.O.] Draw 1 card.`,
  },{
    setId: SetId.OP01,
    setNumber: 81,
    cardName: 'Mocha',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.PunkHazard ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 82,
    cardName: 'Monet',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hashimoto Q' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates, TypeTags.PunkHazard ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP01,
    setNumber: 83,
    cardName: 'Mr.1(Daz.Bonez)',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'touge369' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [Your Turn] If your Leader has the {Baroque Works} type, this Character gains +1000 power for every 2 Events in your trash.`,
  },{
    setId: SetId.OP01,
    setNumber: 84,
    cardName: 'Mr.2.Bon.Kurei(Bentham)',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'BISAI' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] Look at 5 cards from the top of your deck; reveal up to 1 {Baroque Works} type Event card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP01,
    setNumber: 85,
    cardName: 'Mr.3(Galdino)',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Kaito Shibano' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On Play] If your Leader has the {Baroque Works} type, select up to 1 of your opponent's Characters with a cost of 4 or less. The selected Character cannot attack until the end of your opponent's next turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 86,
    cardName: 'Overheat',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, return up to 1 active Character with a cost of 3 or less to the owner's hand.`,
    triggerText: `[Trigger] Return up to 1 card with a cost of 4 or less to the owner's hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 87,
    cardName: 'Officer Agents',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 2,
    effectText: `[Counter] Play up to 1 {Baroque Works} type card with a cost of 3 or less from your hand.`,
    triggerText: `[Trigger] Activate this card's [Counter] effect.`,
  },{
    setId: SetId.OP01,
    setNumber: 88,
    cardName: 'Desert Spada',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, look at 3 cards from the top of your deck and place them at the top or bottom of the deck in any order.`,
    triggerText: `[Trigger] Draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 89,
    cardName: 'Crescent Cutlass',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    cost: 3,
    effectText: `[Counter] If your Leader has the {The Seven Warlords of the Sea} type, return up to 1 Character with a cost of 5 or less to the owner's hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 90,
    cardName: 'Baroque Works',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 1,
    effectText: `[Main] Look at 5 cards from the top of your deck; reveal up to 1 {Baroque Works} type card other than [Baroque Works] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP01,
    setNumber: 91,
    cardName: 'King',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Your Turn] If you have 10 DON!! cards on your field, give all of your opponent's Characters -1000 power.`,
    life: 5,
  },{
    setId: SetId.OP01,
    setNumber: 92,
    cardName: 'Urashima',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 7,
    power: 9000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 93,
    cardName: 'Ulti',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hagane Tsurugi', 'NIJIMAARC' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] ① (You may rest the specified number of DON!! cards in your cost area.): Add up to 1 DON!! card from your DON!! deck and rest it.`,
  },{
    setId: SetId.OP01,
    setNumber: 94,
    cardName: 'Kaido',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Yosuke Adachi', 'shosuke' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 10,
    power: 12000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] DON!! -6 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the {Animal Kingdom Pirates} type, K.O. all Characters other than this Character.`,
  },{
    setId: SetId.OP01,
    setNumber: 95,
    cardName: 'Kyoshirou',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hayaken-sarena' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Draw 1 card if you have 8 or more DON!! cards on your field.`,
  },{
    setId: SetId.OP01,
    setNumber: 96,
    cardName: 'King',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'DAI-XT.', 'DAI-XT.' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 3 or less and up to 1 of your opponent's Characters with a cost of 2 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 97,
    cardName: 'Queen',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Misa Tsutsui', 'Yuu Shimotsuki' ],
    imgObjs: [ '_D.png', 'p_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 6,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains [Rush] during this turn. Then, give up to 1 of your opponent's Characters -2000 power during this turn.
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP01,
    setNumber: 98,
    cardName: 'Kurozumi Orochi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KurozumiClan ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[On Play] Reveal up to 1 [Artificial Devil Fruit SMILE] from your deck and add it to your hand. Then, shuffle your deck.`,
  },{
    setId: SetId.OP01,
    setNumber: 99,
    cardName: 'Kurozumi Semimaru',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KurozumiClan ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `{Kurozumi Clan} type Characters other than your [Kurozumi Semimaru] cannot be K.O.'d in battle.`,
  },{
    setId: SetId.OP01,
    setNumber: 100,
    cardName: 'Kurozumi Higurashi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KurozumiClan ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP01,
    setNumber: 101,
    cardName: 'Sasaki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Yamada Rokkaku.' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] You may trash 1 card from your hand: Add up to 1 DON!! card from your DON!! deck and rest it.`,
  },{
    setId: SetId.OP01,
    setNumber: 102,
    cardName: 'Jack',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Yamada Rokkaku.', 'DAI-XT.' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[When Attacking] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Your opponent trashes 1 card from their hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 103,
    cardName: 'Scratchmen Apoo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akira Kano' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.OnAirPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 104,
    cardName: 'Speed',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP01,
    setNumber: 105,
    cardName: 'Bao Huang',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Mutsumi Sasaki' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `[On Play] Choose 2 cards from your opponent's hand; your opponent reveals those cards.`,
  },{
    setId: SetId.OP01,
    setNumber: 106,
    cardName: 'Basil Hawkins',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hatori Kyoka' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.HawkinsPirates ],
    cost: 4,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Add up to 1 DON!! card from your DON!! deck and rest it.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP01,
    setNumber: 107,
    cardName: 'Babanuki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 108,
    cardName: 'Hitokiri Kamazo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Koushi Rokushiro' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates, TypeTags.SMILE ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On K.O.] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 109,
    cardName: `Who's.Who`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'Anderson', 'Anderson' ],
    imgObjs: [ '_dummy.png', 'p_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [Your Turn] If you have 8 or more DON!! cards on your field, this Character gains +2000 power.`,
  },{
    setId: SetId.OP01,
    setNumber: 110,
    cardName: 'Fukurokuju',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.AnimalKingdomPirates ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP01,
    setNumber: 111,
    cardName: 'Black Maria',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Mutsumi Sasaki' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Block] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains +1000 power during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 112,
    cardName: 'Page One',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Koushi Rokushiro' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Activate: Main] [Once Per Turn] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character can also attack your opponent's active Characters during this turn.`,
  },{
    setId: SetId.OP01,
    setNumber: 113,
    cardName: 'Holedem',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Tsutsui' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On K.O.] Add up to 1 DON!! card from your DON!! deck and rest it.`,
  },{
    setId: SetId.OP01,
    setNumber: 114,
    cardName: 'X.Drake',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Akihiro MIYANO' ],
    imgObjs: [ '_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.Navy, TypeTags.DrakePirates, TypeTags.AnimalKingdomPirates ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 2000,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Your opponent trashes 1 card from their hand.`,
  },{
    setId: SetId.OP01,
    setNumber: 115,
    cardName: `Elephant's Marchoo`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 4,
    effectText: `[Main] K.O. up to 1 of your opponent's Characters with a cost of 2 or less, then add up to 1 DON!! card from your DON!! deck and set it as active.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP01,
    setNumber: 116,
    cardName: `Artificial Devil Fruit SMILE`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 2,
    effectText: `[Main] Look at 5 cards from the top of your deck; play up to 1 {SMILE} type Character card with a cost of 3 or less. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP01,
    setNumber: 117,
    cardName: `Sheep's Horn`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 2,
    effectText: `[Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Rest up to 1 of your opponent's Characters with a cost of 6 or less.`,
  },{
    setId: SetId.OP01,
    setNumber: 118,
    cardName: `Ulti-Mortar`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 1,
    effectText: `[Counter] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, draw 1 card.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP01,
    setNumber: 119,
    cardName: `Thunder Bagua`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 2 or less Life cards, add up to 1 DON!! card from your DON!! deck and rest it.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP01,
    setNumber: 120,
    cardName: 'Shanks',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'Makitoshi', 'Manga', 'Manga' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png', '_SP_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.RedHairedPirates ],
    cost: 9,
    power: 10000,
    attribute: CardAttribute.SLASH,
    effectText: `[Rush] (This card can attack on the turn in which it is played.)
    [When Attacking] Your opponent cannot activate a [Blocker] Character that has 2000 or less power during this battle.`,
  },{
    setId: SetId.OP01,
    setNumber: 121,
    cardName: 'Yamato',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Berry Verrine' ],
    imgObjs: [ '_dummy.png', '_P_dummy.png' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `Also treat this card's name as [Kouzuki Oden] according to the rules.
    [Double Attack] (This card deals 2 damage.)
    [Banish] (When this card deals damage, the target card is trashed without activating its Trigger.)`,
  },
];