import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.OP02,
    setNumber: 1,
    cardName: 'Edward.Newgate',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.WhitebeardPirates ],
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[End of Your Turn] Add 1 card from the top of your Life cards to your hand.`,
    life: 6,
  },{
    setId: SetId.OP02,
    setNumber: 2,
    cardName: 'Monkey.D.Garp',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED, CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Your Turn] When this Leader or any of your Characters is given a DON!! card, give up to 1 of your opponent's Characters with a cost of 7 or less -1 cost during this turn.`,
    life: 4,
  },{
    setId: SetId.OP02,
    setNumber: 3,
    cardName: 'Atmos',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 4,
    cardName: 'Edward.Newgate',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'tatsuya', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.WhitebeardPirates ],
    cost: 9,
    power: 10000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Up to 1 of your Leader gains +2000 power until the start of your next turn. Then, you cannot add Life cards to your hand using your own effects during this turn.
    [DON!! x2] [When Attacking] K.O. up to 1 of your opponent's Characters with 3000 power or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 5,
    cardName: 'Curly.Dadan',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.MountainBandits ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Look at up to 5 cards from the top of your deck; reveal up to 1 red Character with a cost of 1 and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP02,
    setNumber: 6,
    cardName: 'Kingdew',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 7,
    cardName: 'Thatch',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 8,
    cardName: 'Jozu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x1] If you have 2 or less Life cards and your Leader's type includes "Whitebeard Pirates", this Character gains [Rush].
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP02,
    setNumber: 9,
    cardName: 'Squard',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'Hayaken-serena', 'Hayaken-serena' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPiratesAllies ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If your Leader's type includes "Whitebeard Pirates", give up to 1 of your opponent's Characters -4000 power during this turn and add 1 card from the top of your Life cards to your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 10,
    cardName: 'Dogura',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.MountainBandits ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[Activate: Main] You may rest this Character: Play up to 1 red Character other than [Dogura] with a cost of 1 from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 11,
    cardName: 'Vista',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] K.O. up to 1 of your opponent's Characters with 3000 power or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 12,
    cardName: 'Blenheim',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 13,
    cardName: 'Portgas.D.Ace',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'Anime', 'Manga', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Give up to 2 of your opponent's Characters -3000 power during this turn. Then, if your Leader's type includes "Whitebeard Pirates", this Character gains [Rush] during this turn.
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP02,
    setNumber: 14,
    cardName: 'Whitey Bay',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPiratesAllies ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] This Character can also attack your opponent's active Characters.`,
  },{
    setId: SetId.OP02,
    setNumber: 15,
    cardName: 'Makino',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.WindmillVillage ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[Activate: Main] You may rest this Character: Up to 1 of your red Characters with a cost of 1 gains +3000 power during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 16,
    cardName: 'Magura',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.MountainBandits ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Up to 1 of your red Characters with a cost of 1 gains +3000 power during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 17,
    cardName: 'Masked Deuce',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Manga', 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.SpadePirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[DON!! x2] [When Attacking] K.O. up to 1 of your opponent's Characters with 2000 power or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 18,
    cardName: 'Marco',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'otumami', 'Nakano Haito' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] You may trash 1 card with a type including "Whitebeard Pirates" from your hand: If you have 2 or less Life cards, play this Character card from your trash rested.`,
  },{
    setId: SetId.OP02,
    setNumber: 19,
    cardName: 'Rakuyo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[DON!! x1] [Your Turn] All of your Characters with a type including "Whitebeard Pirates" gain +1000 power.`,
  },{
    setId: SetId.OP02,
    setNumber: 20,
    cardName: 'LittleOars Jr.',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Giant, TypeTags.WhitebeardPiratesAllies ],
    cost: 7,
    power: 9000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 21,
    cardName: 'Seaquake',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.WhitebeardPirates ],
    cost: 1,
    effectText: `[Main] If your Leader's type includes "Whitebeard Pirates", K.O. up to 1 of your opponent's Characters with 3000 power or less.`,
    triggerText: `[Trigger] Give up to 1 of your opponent's Leader or Character cards -3000 power during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 22,
    cardName: 'Whitebeard Pirates',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 1,
    effectText: `[Main] Look at 5 cards from the top of your deck; reveal up to 1 Character card with a type including "Whitebeard Pirates" and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP02,
    setNumber: 23,
    cardName: 'You May Be a Fool...but I Still Love You',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.WhitebeardPirates ],
    cost: 1,
    effectText: `[Main] If you have 3 or less Life cards, you cannot add Life cards to your hand using your own effects during this turn.`,
    triggerText: `[Trigger] Up to 1 of your Leader gains +1000 power during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 24,
    cardName: 'Moby Dick',
    cardType: CardType.STAGE,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 2,
    effectText: `[Your Turn] If you have 1 or less Life cards, your [Edward.Newgate] and all your Characters with a type including "Whitebeard Pirates" gain +2000 power.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP02,
    setNumber: 25,
    cardName: `Kin'emon`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] If you have 1 or less Characters, the next time you play a {Land of Wano} type Character card with a cost of 3 or more from your hand during this turn, the cost will be reduced by 1.`,
    life: 5,
  },{
    setId: SetId.OP02,
    setNumber: 26,
    cardName: `Sanji`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Once Per Turn] When you play a Character with no base effect from your hand, if you have 3 or less Characters, set up to 2 of your DON!! cards as active.`,
    life: 4,
  },{
    setId: SetId.OP02,
    setNumber: 27,
    cardName: `Inuarashi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.Minks, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `If all of your DON!! cards are rested, this Character cannot be removed from the field by your opponent's effects.`,
  },{
    setId: SetId.OP02,
    setNumber: 28,
    cardName: `Usopp`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 29,
    cardName: `Carrot`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 1,
    types: [ TypeTags.Minks ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 2000,
    effectText: `[End of Your Turn] Set up to 1 of your DON!! cards as active.`,
  },{
    setId: SetId.OP02,
    setNumber: 30,
    cardName: `Kouzuki Oden`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Misa Matoki', 'TAPIOCA' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] ③ (You may rest the specified number of DON!! cards in your cost area.): Set this Character as active.
    [On K.O.] Play up to 1 green {Land of Wano} type Character card with a cost of 3 from your deck. Then, shuffle your deck.`,
  },{
    setId: SetId.OP02,
    setNumber: 31,
    cardName: `Kouzuki Toki`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'SHIE NANAHARA', 'SHIE NANAHARA' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `If you have a [Kouzuki Oden] Character, this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 32,
    cardName: `Shishilian`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hatori Kyoka' ],
    blockIcon: 1,
    types: [ TypeTags.Minks ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] ② (You may rest the specified number of DON!! cards in your cost area.): Set up to 1 of your {Minks} type Characters with a cost of 5 or less as active.`,
  },{
    setId: SetId.OP02,
    setNumber: 33,
    cardName: `Jinbe`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.FishMan, TypeTags.StrawHatCrew ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 34,
    cardName: `Tony Tony.Chopper`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Animal, TypeTags.StrawHatCrew ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] Rest up to 1 of your opponent's Characters with a cost of 2 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 35,
    cardName: `Trafalgar Law`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'DAI-XT.' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.HeartPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may return this Character to the owner's hand: Play up to 1 Character with a cost of 3 from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 36,
    cardName: `Nami`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play]/[When Attacking] ➀ (You may rest the specified number of DON!! cards in your cost area.): Look at 3 cards from the top of your deck; reveal up to 1 {FILM} type card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP02,
    setNumber: 37,
    cardName: `Nico Robin`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[On Play] Play up to 1 {FILM} or {Straw Hat Crew} type Character card with a cost of 2 or less from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 38,
    cardName: `Nekomamushi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hayaken-sarena' ],
    blockIcon: 1,
    types: [ TypeTags.Minks, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 39,
    cardName: `Franky`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 40,
    cardName: `Brook`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Play up to 1 {FILM} or {Straw Hat Crew} type Character card with a cost of 3 or less from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 41,
    cardName: `Monkey.D.Luffy`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] Play up to 1 {FILM} or {Straw Hat Crew} type Character card with a cost of 4 or less from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 42,
    cardName: `Yamato`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'NIJIMAARC' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `Also treat this card's name as [Kouzuki Oden] according to the rules.
    [On Play] Rest up to 1 of your opponent's Characters with a cost of 6 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 43,
    cardName: `Roronoa Zoro`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 44,
    cardName: `Wanda`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 1,
    types: [ TypeTags.Minks ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Play up to 1 {Minks} type Character card other than [Wanda] with a cost of 3 or less from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 45,
    cardName: `Three Sword Style Oni Giri`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 3,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +6000 power during this battle. Then, play up to 1 Character card with a cost of 3 or less and no base effect from your hand.`,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Leader or Character cards with a cost of 5 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 46,
    cardName: `Diable Jambe Venaison Shoot`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 2,
    effectText: `[Main] K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] Play up to 1 Character card with a cost of 4 or less and no base effect from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 47,
    cardName: `Paradise Totsuka`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    effectText: `[Main] Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 48,
    cardName: `Land of Wano`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 1,
    effectText: `[Activate: Main] You may trash 1 {Land of Wano} type card from your hand and rest this Stage: Set up to 1 of your DON!! cards as active.`,
  },{
    setId: SetId.OP02,
    setNumber: 49,
    cardName: `Emporio.Ivankov`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.RevolutionaryArmy ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[End of Your Turn] If you have 0 cards in your hand, draw 2 cards.`,
    life: 5,
  },{
    setId: SetId.OP02,
    setNumber: 50,
    cardName: `Inazuma`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.RevolutionaryArmy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `If you have 1 or less cards in your hand, this Character gains +2000 power.
    [Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 51,
    cardName: `Emporio.Ivankov`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'akagi', 'EBIMO' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.RevolutionaryArmy ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Draw card(s) so that you have 3 cards in your hand and then play up to 1 blue {Impel Down} type Character card with a cost of 6 or less from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 52,
    cardName: `Cabaji`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.BuggyPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] If you have [Mohji], draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 53,
    cardName: `Crocodile`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.FormerBaroqueWorks ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 54,
    cardName: `Gecko Moria`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'nukadokomogera' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 55,
    cardName: `Dracule Mihawk`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 56,
    cardName: `Donquixote Doflamingo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Mitsuaki Matsumoto' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Look at 3 cards from the top of your deck and place them at the top or bottom of the deck in any order.
    [DON!! x1] [When Attacking] You may trash 1 card from your hand: Place up to 1 of your opponent's Characters with a cost of 1 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP02,
    setNumber: 57,
    cardName: `Bartholomew Kuma`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.RevolutionaryArmy ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[On Play] Look at 2 cards from the top of your deck; reveal up to 1 {The Seven Warlords of the Sea} type card and add it to your hand. Then, place the rest at the top or bottom of the deck in any order.`,
  },{
    setId: SetId.OP02,
    setNumber: 58,
    cardName: `Buggy`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Denim2', 'Ryuda' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.BuggyPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 blue {Impel Down} type card other than [Buggy] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP02,
    setNumber: 59,
    cardName: `Boa Hancock`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'nuisuke', 'nuisuke' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.TheSevenWarlordsOfTheSea, TypeTags.KujaPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[When Attacking] Draw 1 card and trash 1 card from your hand. Then, trash up to 3 cards from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 60,
    cardName: `Mohji`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.BuggyPirates ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 61,
    cardName: `Morley`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.Giant, TypeTags.RevolutionaryArmy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[When Attacking] If you have 1 or less cards in your hand, your opponent cannot activate the [Blocker] of any Character with a cost of 5 or less during this battle.`,
  },{
    setId: SetId.OP02,
    setNumber: 62,
    cardName: `Monkey.D.Luffy`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'otumami', 'AKIRA EGAWA' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.StrawHatCrew ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play]/[When Attacking] You may trash 2 cards from your hand: Return up to 1 Character with a cost of 4 or less to the owner's hand. Then, this Character gains [Double Attack] during this turn.
    (This card deals 2 damage.)`,
  },{
    setId: SetId.OP02,
    setNumber: 63,
    cardName: `Mr.1(Daz.Bonez)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'TAPIOCA' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.FormerBaroqueWorks ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Add up to 1 blue Event card with a cost of 1 from your trash to your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 64,
    cardName: `Mr.2.Bon.Kurei(Bentham)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'phima' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.FormerBaroqueWorks ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] You may trash 1 card from your hand: Place up to 1 Character with a cost of 2 or less at the bottom of the owner's deck. Then, at the end of this battle, place this Character at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP02,
    setNumber: 65,
    cardName: `Mr.3(Galdino)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.FormerBaroqueWorks ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [End of Your Turn] You may trash 1 card from your hand: Set this Character as active.`,
  },{
    setId: SetId.OP02,
    setNumber: 66,
    cardName: `Impel Down All Stars`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 1,
    effectText: `[Main] You may trash 2 cards from your hand: If your Leader has the {Impel Down} type, draw up to 2 cards.`,
    triggerText: `[Trigger] Draw 2 cards.`,
  },{
    setId: SetId.OP02,
    setNumber: 67,
    cardName: `Arabesque Brick Fist`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.ImpelDown ],
    cost: 2,
    effectText: `[Main] Return up to 1 Character with a cost of 4 or less to the owner's hand.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP02,
    setNumber: 68,
    cardName: `Gum-Gum Rain`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.StrawHatCrew ],
    cost: 0,
    effectText: `[Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.`,
    triggerText: `[Trigger] Return up to 1 Character with a cost of 2 or less to the owner's hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 69,
    cardName: `DEATH WINK`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.RevolutionaryArmy ],
    cost: 3,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +6000 power during this battle. Then, draw cards so that you have 2 cards in your hand.`,
    triggerText: `[Trigger] Return up to 1 Character with a cost of 7 or less to the owner's hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 70,
    cardName: `New Kama Land`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 1,
    effectText: `[Activate: Main] You may rest this Stage: If your Leader is [Emporio.Ivankov], draw 1 card and trash 1 card from your hand. Then, trash up to 3 cards from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 71,
    cardName: `Magellan`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Your Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck, this Leader gains +1000 power during this turn.`,
    life: 5,
  },{
    setId: SetId.OP02,
    setNumber: 72,
    cardName: `Zephyr`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.PURPLE, CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.NeoNavy ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] DON!! -4 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 3 or less. Then, this Leader gains +1000 power during this turn.`,
    life: 4,
  },{
    setId: SetId.OP02,
    setNumber: 73,
    cardName: `Little Sadi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'phima', 'Hashimoto Q' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[On Play] Play up to 1 {Jailer Beast} type Character card from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 74,
    cardName: `Saldeath`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `Your [Blugori] gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 75,
    cardName: `Shiki`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.GoldenLionPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 2000,
    triggerText: `[Trigger] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
  },{
    setId: SetId.OP02,
    setNumber: 76,
    cardName: `Shiryu`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'shosuke' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 1 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 77,
    cardName: `Solitaire`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'NIJIMAARC' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 78,
    cardName: `Daifugo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[On Play] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play up to 1 {SMILE} type Character card other than [Daifugo] with a cost of 3 or less from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 79,
    cardName: `Douglas Bullet`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.ThePiratesFest ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 80,
    cardName: `Dobon`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'shosuke' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.SMILE ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 81,
    cardName: `Domino`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'UGUME' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 82,
    cardName: `Byrnndi World`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.WorldPirates ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] DON!! -8 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains +792000 power during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 83,
    cardName: `Hannyabal`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Hayaken-sarena' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 purple {Impel Down} type card other than [Hannyabal] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP02,
    setNumber: 84,
    cardName: `Blugori`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.ImpelDown ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 85,
    cardName: `Magellan`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Your opponent returns 1 DON!! card from their field to their DON!! deck.
    [Opponent's Turn] When this Character is K.O.'d, your opponent returns 2 DON!! cards from their field to their DON!! deck.`,
  },{
    setId: SetId.OP02,
    setNumber: 86,
    cardName: `Minokoala`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'touge369', 'touge369' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.JailerBeast ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] If your Leader has the {Impel Down} type, add up to 1 DON!! card from your DON!! deck and rest it.`,
  },{
    setId: SetId.OP02,
    setNumber: 87,
    cardName: `Minotaur`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.JailerBeast ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Double Attack] (This card deals 2 damage.)
    [On K.O.] If your Leader has the {Impel Down} type, add up to 1 DON!! card from your DON!! deck and rest it.`,
  },{
    setId: SetId.OP02,
    setNumber: 88,
    cardName: `Sphinx`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.ImpelDown ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 89,
    cardName: `Judgment of Hell`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 2,
    effectText: `[Counter] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Give up to a total of 2 of your opponent's Leader or Character cards -3000 power during this turn.`,
    triggerText: `[Trigger] If your opponent has 6 or more DON!! cards on their field, your opponent returns 1 DON!! card from their field to their DON!! deck.`,
  },{
    setId: SetId.OP02,
    setNumber: 90,
    cardName: `Hydra`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 1,
    effectText: `[Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Give up to 1 of your opponent's Characters -3000 power during this turn.`,
    triggerText: `[Trigger] If your opponent has 6 or more DON!! cards on their field, your opponent returns 1 DON!! card from their field to their DON!! deck.`,
  },{
    setId: SetId.OP02,
    setNumber: 91,
    cardName: `Venom Road`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 3,
    effectText: `[Main] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
    triggerText: `[Trigger] If your opponent has 6 or more DON!! cards on their field, your opponent returns 1 DON!! card from their field to their DON!! deck.`,
  },{
    setId: SetId.OP02,
    setNumber: 92,
    cardName: `Impel Down`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown ],
    cost: 1,
    effectText: `[Activate: Main] You may trash 1 card from your hand and rest this Stage: Look at 3 cards from the top of your deck; reveal up to 1 {Impel Down} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP02,
    setNumber: 93,
    cardName: `Smoker`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] [Activate: Main] [Once Per Turn] Give up to 1 of your opponent's Characters -1 cost during this turn. Then, if there is a Character with a cost of 0, this Leader gains +1000 power during this turn.`,
    life: 5,
  },{
    setId: SetId.OP02,
    setNumber: 94,
    cardName: `Isuka`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [Once Per Turn] When this Character battles and K.O.'s your opponent's Character, set this Character as active.`,
  },{
    setId: SetId.OP02,
    setNumber: 95,
    cardName: `Onigumo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'nukadokomogera' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `If there is a Character with a cost of 0, this Character gains [Banish].
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
  },{
    setId: SetId.OP02,
    setNumber: 96,
    cardName: `Kuzan`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Makitoshi', 'tatsuya' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Draw 1 card.
    [When Attacking] Give up to 1 of your opponent's Characters -4 cost during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 97,
    cardName: `Komille`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 98,
    cardName: `Koby`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'kankurou', 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[On Play] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 3 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 99,
    cardName: `Sakazuki`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'tatsuya', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 100,
    cardName: `Jango`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'jugemt' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `If you have [Fullbody], this Character cannot be K.O.'d in battle.`,
  },{
    setId: SetId.OP02,
    setNumber: 101,
    cardName: `Strawberry`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] If there is a Character with a cost of 0, your opponent cannot activate the [Blocker] of any Character with a cost of 5 or less during this battle.`,
  },{
    setId: SetId.OP02,
    setNumber: 102,
    cardName: `Smoker`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `This Character cannot be K.O.'d by effects.
    [When Attacking] If there is a Character with a cost of 0, this Character gains +2000 power during this battle.`,
  },{
    setId: SetId.OP02,
    setNumber: 103,
    cardName: `Sengoku`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] Give up to 1 of your opponent's Characters -2 cost during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 104,
    cardName: `Sentomaru`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'jugemt' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP02,
    setNumber: 105,
    cardName: `Tashigi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] Give up to 1 of your opponent's Characters -3 cost during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 106,
    cardName: `Tsuru`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    counter: 2000,
    effectText: `[On Play] Give up to 1 of your opponent's Characters -2 cost during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 107,
    cardName: `Doberman`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 108,
    cardName: `Donquixote Rosinante`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.BOX_TOPPER ],
    artists: [ 'Mitsuaki Matsumoto', 'Mitsuaki Matsumoto' ],
    blockIcon: 1,
    types: [ TypeTags.Navy, TypeTags.DonquixotePirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 109,
    cardName: `Jaguar.D.Saul`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Giant, TypeTags.Navy ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 110,
    cardName: `Hina`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Block] Select up to 1 of your opponent's Characters with a cost of 6 or less. The selected Character cannot attack during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 111,
    cardName: `Fullbody`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Moopic' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[When Attacking] If you have [Jango], this card gains +3000 power during this battle.`,
  },{
    setId: SetId.OP02,
    setNumber: 112,
    cardName: `Bell-mère`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'UGUME' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
    effectText: `[Activate: Main] You may rest this Character: Give up to 1 of your opponent's Characters -1 cost during this turn. Then, up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 113,
    cardName: `Helmeppo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[When Attacking] Give up to 1 of your opponent's Characters -2 cost during this turn. Then, if there is a Character with a cost of 0, this Character gains +2000 power during this battle.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP02,
    setNumber: 114,
    cardName: `Borsalino`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anderson', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Opponent's Turn] This Character gains +1000 power and cannot be K.O.'d by effects.
    [Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP02,
    setNumber: 115,
    cardName: `Monkey.D.Garp`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Studio Vigor Co.,Ltd', 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x2] [When Attacking] K.O. up to 1 of your opponent's Characters with a cost of 0.`,
  },{
    setId: SetId.OP02,
    setNumber: 116,
    cardName: `Yamakaji`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'touge369' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP02,
    setNumber: 117,
    cardName: `Ice Age`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    effectText: `[Main] Give up to 1 of your opponent's Characters -5 cost during this turn.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 3 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 118,
    cardName: `Yasakani Sacred Jewel`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    effectText: `[Counter] You may trash 1 card from your hand: Select up to 1 of your Characters. The selected Character cannot be K.O.'d during this battle.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Stages with a cost of 3 or less.`,
  },{
    setId: SetId.OP02,
    setNumber: 119,
    cardName: `Meteor Volcano`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    effectText: `[Main] K.O. up to 1 of your opponent's Characters with a cost of 1 or less.`,
    triggerText: `[Trigger] Draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.OP02,
    setNumber: 120,
    cardName: `Uta`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Demizu Posuka' ],
    blockIcon: 1,
    types: [ TypeTags.FILM ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Your Leader and all of your Characters gain +1000 power until the start of your next turn.`,
  },{
    setId: SetId.OP02,
    setNumber: 121,
    cardName: `Kuzan`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Nijihayashi', 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.FormerNavy ],
    cost: 10,
    power: 10000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Your Turn] Give all of your opponent's Characters -5 cost.
    [On Play] K.O. up to 1 of your opponent's Characters with a cost of 0.`,
  },
];