import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.OP03,
    setNumber: 1,
    cardName: 'Portgas.D.Ace',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'Anime', 'Anderson', 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `When this Leader attacks or is attacked, you may trash any number of Event or Stage cards from your hand. This Leader gains +1000 power during this battle for every card trashed.`,
    life: 5,
  },{
    setId: SetId.OP03,
    setNumber: 2,
    cardName: 'Adio',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.ODYSSEY ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[DON!! x1] [When Attacking] Your opponent cannot activate a [Blocker] Character that has 2000 or less power during this battle.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 3,
    cardName: 'Izo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.WhitebeardPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.RANGED,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 card with a type including "Whitebeard Pirates" other than [Izo] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 4,
    cardName: 'Curiel',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.RANGED,
    effectText: `This Character cannot attack a Leader on the turn in which it is played.
    [DON!! x1] This Character gains [Rush].
    (This card can attack on the turn in which it is played.)`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 5,
    cardName: 'Thatch',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'touge369' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] This Character gains +2000 power during this turn. Then, trash this Character at the end of this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 6,
    cardName: 'Speed Jil',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 7,
    cardName: 'Namule',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.WhitebeardPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 8,
    cardName: 'Buggy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'akagi' ],
    blockIcon: 1,
    types: [ TypeTags.BuggyPirates ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `This Character cannot be K.O.'d in battle by <Slash> attribute cards.
    [On Play] Look at 5 cards from the top of your deck; reveal up to 1 red Event and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP03,
    setNumber: 9,
    cardName: 'Haruta',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] Give up to 1 rested DON!! card to your Leader or 1 of your Characters.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 10,
    cardName: 'Fossa',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 11,
    cardName: 'Blamenco',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [When Attacking] Give up to 1 of your opponent's Characters -2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 12,
    cardName: 'Marshall.D.Teach',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'TAPIOCA' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] You may trash 1 of your red Characters with 4000 power or more: Draw 1 card. Then, this Character gains +1000 power during this battle.`,
  },{
    setId: SetId.OP03,
    setNumber: 13,
    cardName: 'Marco',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Studio Vigor Co.,Ltd', 'tatsuya' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Your Turn] [On Play] K.O. up to 1 of your opponent's Characters with 3000 power or less.
    [On K.O.] You may trash 1 Event from your hand: You may play this Character card from your trash rested.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 14,
    cardName: 'Monkey.D.Garp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] Play up to 1 red Character card with a cost of 1 from your hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 15,
    cardName: 'Lim',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'NIJIMAARC' ],
    blockIcon: 1,
    types: [ TypeTags.ODYSSEY ],
    cost: 3,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [Opponent's Turn] When this Character is K.O.'d, give up to 1 of your opponent's Leader or Character cards -2000 power during this turn.`,
  },{
    setId: SetId.OP03,
    setNumber: 16,
    cardName: 'Flame Emperor',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 7,
    effectText: `[Main] If your Leader is [Portgas.D.Ace], K.O. up to 1 of your opponent's Characters with 8000 power or less, and your Leader gains [Double Attack] and +3000 power during this turn.
    (This card deals 2 damage.)`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with 6000 power or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 17,
    cardName: 'Cross Fire',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 2,
    effectText: `[Main]/[Counter] If your Leader's type includes "Whitebeard Pirates", give up to 1 of your opponent's Characters -4000 power during this turn.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP03,
    setNumber: 18,
    cardName: 'Fire Fist',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Manga', 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 3,
    effectText: `[Main] You may trash 1 Event from your hand: K.O. up to 1 of your opponent's Characters with 5000 power or less and up to 1 of your opponent's Characters with 4000 power or less.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with 5000 power or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 19,
    cardName: 'Fiery Doll',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 2,
    effectText: `[Main] Your Leader gains +4000 power during this turn.`,
    triggerText: `[Trigger] Give up to 1 of your opponent's Leader or Character cards -10000 power during this turn.`,
  },{
    setId: SetId.OP03,
    setNumber: 20,
    cardName: 'Striker',
    cardType: CardType.STAGE,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.WhitebeardPirates ],
    cost: 1,
    effectText: `[Activate: Main] ② (You may rest the specified number of DON!! cards in your cost area.) You may rest this Stage: If your Leader is [Portgas.D.Ace], look at 5 cards from the top of your deck; reveal up to 1 Event and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP03,
    setNumber: 21,
    cardName: 'Kuro',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BlackCatPirates ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] ③ (You may rest the specified number of DON!! cards in your cost area.) You may rest 2 of your {East Blue} type Characters: Set this Leader as active, and rest up to 1 of your opponent's Characters with a cost of 5 or less.`,
    life: 5,
  },{
    setId: SetId.OP03,
    setNumber: 22,
    cardName: 'Arlong',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.EastBlue, TypeTags.ArlongPirates ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x2] [When Attacking] ① (You may rest the specified number of DON!! cards in your cost area.): Play up to 1 Character card with a cost of 4 or less and a [Trigger] from your hand.`,
    life: 4,
  },{
    setId: SetId.OP03,
    setNumber: 23,
    cardName: 'Alvida',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'phima' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.AlvidaPirates ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 24,
    cardName: 'Gin',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.KriegPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If your Leader has the {East Blue} type, rest up to 2 of your opponent's Characters with a cost of 4 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 25,
    cardName: 'Krieg',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Ryuda', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.KriegPirates ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.RANGED,
    effectText: `[On Play] You may trash 1 card from your hand: K.O. up to 2 of your opponent's rested Characters with a cost of 4 or less.
    [DON!! x1] This Character gains [Double Attack].
    (This card deals 2 damage.)`,
  },{
    setId: SetId.OP03,
    setNumber: 26,
    cardName: 'Kuroobi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.EastBlue, TypeTags.ArlongPirates ],
    cost: 4,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If your Leader has the {East Blue} type, rest up to 1 of your opponent's Characters.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 27,
    cardName: 'Sham',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Minato Sashima' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BlackCatPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If your Leader has the {East Blue} type, rest up to 1 of your opponent's Characters with a cost of 2 or less and, if you don't have [Buchi], play up to 1 [Buchi] from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 28,
    cardName: 'Jango',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BlackCatPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Choose one:
    • Set up to 1 of your {East Blue} type Leader or Character cards with a cost of 6 or less as active.
    • Rest this Character and up to 1 of your opponent's Characters.`,
  },{
    setId: SetId.OP03,
    setNumber: 29,
    cardName: 'Chew',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.EastBlue, TypeTags.ArlongPirates ],
    cost: 4,
    power: 3000,
    attribute: CardAttribute.RANGED,
    effectText: `[On Play] K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 30,
    cardName: 'Nami',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'nuisuke' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.ArlongPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 green {East Blue} type card other than [Nami] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 31,
    cardName: 'Pearl',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hayaken-sarena' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.KriegPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 32,
    cardName: 'Buggy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Ryuda' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BuggyPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `This Character cannot be K.O.'d in battle by <Slash> attribute cards.`,
  },{
    setId: SetId.OP03,
    setNumber: 33,
    cardName: 'Hatchan',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Moopic' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.EastBlue, TypeTags.ArlongPirates ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SLASH,
    triggerText: `[Trigger] If your Leader has the {East Blue} type, play this card.`,
    counter: 2000,
  },{
    setId: SetId.OP03,
    setNumber: 34,
    cardName: 'Buchi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BlackCatPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] K.O. up to 1 of your opponent's rested Characters with a cost of 2 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 35,
    cardName: 'Momoo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.EastBlue ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 36,
    cardName: 'Out-of-the-Bag',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BlackCatPirates ],
    cost: 3,
    effectText: `[Main] You may rest 1 of your {East Blue} type Characters: Set up to 1 of your [Kuro] cards as active.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 37,
    cardName: 'Tooth Attack',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.EastBlue, TypeTags.ArlongPirates ],
    cost: 1,
    effectText: `[Main] You may rest 1 of your {East Blue} type Characters: K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
    triggerText: `[Trigger] Play up to 1 Character card with a cost of 4 or less and a [Trigger] from your hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 38,
    cardName: 'Deathly Poison Gas Bomb MH5',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.KriegPirates ],
    cost: 1,
    effectText: `[Main] Rest up to 2 of your opponent's Characters with a cost of 2 or less.`,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 39,
    cardName: 'One, Two, Jango',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BlackCatPirates ],
    cost: 1,
    effectText: `[Main] Rest up to 1 of your opponent's Characters with a cost of 1 or less. Then, up to 1 of your Characters gains +1000 power during this turn.`,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 40,
    cardName: 'Nami',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    power: 5000,
    attribute: CardAttribute.WISDOM,
    effectText: `When your deck is reduced to 0, you win the game instead of losing, according to the rules.
    [DON!! x1] When this Leader's attack deals damage to your opponent's Life, you may trash 1 card from the top of your deck.`,
    life: 5,
  },{
    setId: SetId.OP03,
    setNumber: 41,
    cardName: 'Usopp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Studio Vigor Co.,Ltd', 'Denim2' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[Rush] (This card can attack on the turn in which it is played.)
    [DON!! x1] When this Character's attack deals damage to your opponent's Life, you may trash 7 cards from the top of your deck.`,
  },{
    setId: SetId.OP03,
    setNumber: 42,
    cardName: `Usopp's Pirate Crew`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Add up to 1 blue [Usopp] from your trash to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 43,
    cardName: `Gaimon`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `When you deal damage to your opponent's Life, you may trash 3 cards from the top of your deck. If you do, trash this Character.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 44,
    cardName: `Kaya`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'UGUME' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Draw 2 cards and trash 2 cards from your hand.`,
    counter: 2000,
  },{
    setId: SetId.OP03,
    setNumber: 45,
    cardName: `Carne`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [Opponent's Turn] If you have 20 or less cards in your deck, this Character gains +3000 power.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 46,
    cardName: `Genzo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'touge369' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 47,
    cardName: `Zeff`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Mitsuaki Matsumoto' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] When this Character's attack deals damage to your opponent's Life, you may trash 7 cards from the top of your deck.
    [On Play] Return up to 1 Character with a cost of 3 or less to the owner's hand, and you may trash 2 cards from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 48,
    cardName: `Nojiko`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hatori Kyoka' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] If your Leader is [Nami], return up to 1 of your opponent's Characters with a cost of 5 or less to the owner's hand.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 49,
    cardName: `Patty`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If you have 20 or less cards in your deck, return up to 1 Character with a cost of 3 or less to the owner's hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 50,
    cardName: `Boodle`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] You may trash 1 card from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 51,
    cardName: `Bell-mère`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[DON!! x1] When this Character's attack deals damage to your opponent's Life, you may trash 7 cards from the top of your deck.
    [On K.O.] You may trash 3 cards from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 52,
    cardName: `Merry`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 53,
    cardName: `Yosaku & Johnny`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'TAPIOCA' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] If you have 20 or less cards in your deck, this Character gains +2000 power.`,
  },{
    setId: SetId.OP03,
    setNumber: 54,
    cardName: `Usopp's Rubber Band of Doom!!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, you may trash 1 card from the top of your deck.`,
    triggerText: `[Trigger] Draw 1 card and you may trash 1 card from the top of your deck.`,
  },{
    setId: SetId.OP03,
    setNumber: 55,
    cardName: `Gum-Gum Giant Gavel`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Counter] You may trash 1 card from your hand: Up to 1 of your Leader gains +4000 power during this battle. Then, you may trash 2 cards from the top of your deck.`,
    triggerText: `[Trigger] Return up to 1 Character with a cost of 4 or less to the owner's hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 56,
    cardName: `Sanji's Pilaf`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 3,
    effectText: `[Main] Draw 2 cards.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP03,
    setNumber: 57,
    cardName: `Three Thousand Worlds`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.StrawHatCrew ],
    cost: 4,
    effectText: `[Main] Place up to 1 Character with a cost of 5 or less at the bottom of the owner's deck.`,
    triggerText: `[Trigger] Place up to 1 Character with a cost of 3 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP03,
    setNumber: 58,
    cardName: 'Iceburg',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    power: 5000,
    attribute: CardAttribute.WISDOM,
    effectText: `This Leader cannot attack.
    [Activate: Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may rest this Leader: Play up to 1 {Galley-La Company} type Character card with a cost of 5 or less from your hand.`,
    life: 5,
  },{
    setId: SetId.OP03,
    setNumber: 59,
    cardName: `Kaku`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains [Banish] during this battle.
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 60,
    cardName: `Kalifa`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Sunohara' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.WISDOM,
    effectText: `[When Attacking] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Draw 2 cards and trash 1 card from your hand.`,
    counter: 2000,
  },{
    setId: SetId.OP03,
    setNumber: 61,
    cardName: `Kiwi & Mozu`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.TheFrankyFamily ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 62,
    cardName: `Kokoro`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Merfolk, TypeTags.WaterSeven ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Water Seven} type card other than [Kokoro] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 63,
    cardName: `Zambai`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.TheFrankyFamily ],
    cost: 3,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the {Water Seven} type, draw 1 card.`,
  },{
    setId: SetId.OP03,
    setNumber: 64,
    cardName: `Tilestone`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On K.O.] If your Leader has the {Galley-La Company} type, add up to 1 DON!! card from your DON!! deck and rest it.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 65,
    cardName: `Chimney & Gonbe`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.WaterSeven ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 66,
    cardName: `Paulie`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'touge369', 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] ➁ (You may rest the specified number of DON!! cards in your cost area.): Add up to 1 DON!! card from your DON!! deck and set it as active. Then, if you have 8 or more DON!! cards on your field, K.O. up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 67,
    cardName: `Peepley Lulu`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[DON!! x1] [When Attacking] If your Leader has the {Galley-La Company} type, add up to 1 DON!! card from your DON!! deck and rest it.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 68,
    cardName: `Minozebra`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'shosuke' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.JailerBeast ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Banish] (When this card deals damage, the target card is trashed without activating its Trigger.)
    [On K.O.] If your Leader has the {Impel Down} type, add up to 1 DON!! card from your DON!! deck and rest it.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 69,
    cardName: `Minorhinoceros`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.ImpelDown, TypeTags.JailerBeast ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On K.O.] If your Leader has the {Impel Down} type, draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 70,
    cardName: `Monkey.D.Luffy`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.StrawHatCrew ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may trash 1 Character card with a cost of 5 from your hand: This Character gains [Rush] during this turn.
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP03,
    setNumber: 71,
    cardName: `Rob Lucci`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Denim2' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Rest up to 1 of your opponent's Characters with a cost of 5 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 72,
    cardName: `Gum-Gum Jet Gatling`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.StrawHatCrew ],
    cost: 0,
    effectText: `[Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP03,
    setNumber: 73,
    cardName: `Hull Dismantler Slash`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.TheFrankyFamily ],
    cost: 1,
    effectText: `[Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the {Water Seven} type, K.O. up to 1 of your opponent's Characters with a cost of 2 or less.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP03,
    setNumber: 74,
    cardName: `Top Knot`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 2,
    effectText: `[Main] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Place up to 1 of your opponent's Characters with a cost of 4 or less at the bottom of the owner's deck.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP03,
    setNumber: 75,
    cardName: `Galley-La Company`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 3,
    effectText: `[Activate: Main] You may rest this Stage: If your Leader is [Iceburg], add up to 1 DON!! card from your DON!! deck and rest it.`,
  },{
    setId: SetId.OP03,
    setNumber: 76,
    cardName: 'Rob Lucci',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Your Turn] [Once Per Turn] You may trash 2 cards from your hand: When your opponent's Character is K.O.'d, set this Leader as active.`,
    life: 5,
  },{
    setId: SetId.OP03,
    setNumber: 77,
    cardName: 'Charlotte Linlin',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLACK, CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x2] [When Attacking] ② (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: If you have 1 or less Life cards, add up to 1 card from the top of your deck to the top of your Life cards.`,
    life: 4,
  },{
    setId: SetId.OP03,
    setNumber: 78,
    cardName: 'Issho',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'nukadokomogera', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 8,
    power: 9000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [Your Turn] Give all of your opponent's Characters -3 cost.
    [On Play] If your opponent has 6 or more cards in their hand, trash 2 cards from your opponent's hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 79,
    cardName: 'Vergo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'shosuke' ],
    blockIcon: 1,
    types: [ TypeTags.Navy, TypeTags.DonquixotePirates ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] This Character cannot be K.O.'d in battle.`,
    counter: 2000,
  },{
    setId: SetId.OP03,
    setNumber: 80,
    cardName: 'Kaku',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'SENNSU', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] You may place 2 cards with a type including "CP" from your trash at the bottom of your deck in any order: K.O. up to 1 of your opponent's Characters with a cost of 3 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 81,
    cardName: 'Kalifa',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'phima', 'Hashimoto Q' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Draw 2 cards and trash 2 cards from your hand. Then, give up to 1 of your opponent's Characters -2 cost during this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP03,
    setNumber: 82,
    cardName: 'Kumadori',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 83,
    cardName: 'Corgy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.WorldGovernment ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at 5 cards from the top of your deck and trash up to 2 cards. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 84,
    cardName: 'Jerry',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.CP6 ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 85,
    cardName: 'Jabra',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 86,
    cardName: 'Spandam',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'DAI-XT.', 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If your Leader's type includes "CP", look at 3 cards from the top of your deck; reveal up to 1 card with a type including "CP" other than [Spandam] and add it to your hand. Then, trash the rest.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 87,
    cardName: 'Nero',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'NIJIMAARC' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 88,
    cardName: 'Fukurou',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `This Character cannot be K.O.'d by effects.
    [Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 89,
    cardName: 'Brannew',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at 3 cards from the top of your deck; reveal up to 1 {Navy} type card other than [Brannew] and add it to your hand. Then, trash the rest.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 90,
    cardName: 'Blueno',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Hayaken-sarena' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] This Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] Play up to 1 Character card with a type including "CP" and a cost of 4 or less from your trash rested.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 91,
    cardName: 'Helmeppo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Sunohara' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Set the cost of up to 1 of your opponent's Characters with no base effect to 0 during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 92,
    cardName: 'Rob Lucci',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'otumami', 'AKIRA EGAWA' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] You may place 2 cards with a type including "CP" from your trash at the bottom of your deck in any order: This Character gains [Rush] during this turn.
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP03,
    setNumber: 93,
    cardName: 'Wanze',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.CP7 ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] You may trash 1 card from your hand: If your Leader's type includes "CP", K.O. up to 1 of your opponent's Characters with a cost of 1 or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 94,
    cardName: 'Air Door',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 4,
    effectText: `[Main] If your Leader's type includes "CP", look at 5 cards from the top of your deck; play up to 1 Character card with a type including "CP" and a cost of 5 or less. Then, trash the rest.`,
    triggerText: `[Trigger] Play up to 1 black Character card with a cost of 3 or less from your trash.`,
  },{
    setId: SetId.OP03,
    setNumber: 95,
    cardName: 'Soap Sheep',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 1,
    effectText: `[Main] Give up to 2 of your opponent's Characters -2 cost during this turn.`,
    triggerText: `[Trigger] Your opponent trashes 1 card from their hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 96,
    cardName: 'Tempest Kick Sky Slicer',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 2,
    effectText: `[Main] K.O. up to 1 of your opponent's Characters with a cost of 0 or your opponent's Stages with a cost of 3 or less.`,
    triggerText: `[Trigger] Draw 2 cards.`,
  },{
    setId: SetId.OP03,
    setNumber: 97,
    cardName: 'Six King Pistol',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.CP9 ],
    cost: 0,
    effectText: `[Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.`,
    triggerText: `[Trigger] Draw 1 card. Then, K.O. up to 1 of your opponent's Characters with a cost of 1 or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 98,
    cardName: 'Enies Lobby',
    cardType: CardType.STAGE,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.WorldGovernment ],
    cost: 2,
    effectText: `[Activate: Main] You may rest this Stage: If your Leader's type includes "CP", give up to 1 of your opponent's Characters -2 cost during this turn.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP03,
    setNumber: 99,
    cardName: 'Charlotte Katakuri',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [When Attacking] Look at up to 1 card from the top of your or your opponent's Life cards, and place it at the top or bottom of the Life cards. Then, this Leader gains +1000 power during this battle.`,
    life: 5,
  },{
    setId: SetId.OP03,
    setNumber: 100,
    cardName: 'Kingbaum',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    triggerText: `[Trigger] You may trash 1 card from the top or bottom of your Life cards: Play this card.`,
  },{
    setId: SetId.OP03,
    setNumber: 101,
    cardName: 'Camie',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Merfolk ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 102,
    cardName: 'Sanji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'SHIE NANAHARA' ],
    blockIcon: 1,
    types: [ TypeTags.TheVinsmokeFamily ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x2] [When Attacking] You may add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 card from the top of your deck to the top of your Life cards.`,
    counter: 2000,
  },{
    setId: SetId.OP03,
    setNumber: 103,
    cardName: 'Bobbin the Disposer',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 104,
    cardName: 'Shirley',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'jugemt' ],
    blockIcon: 1,
    types: [ TypeTags.Merfolk ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] Look at up to 1 card from the top of your or your opponent's Life cards, and place it at the top or bottom of the Life cards.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 105,
    cardName: 'Shirley',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] [When Attacking] You may trash 1 card with a [Trigger] from your hand: This Character gains +3000 power during this battle.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 106,
    cardName: 'Charlotte Opera',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 107,
    cardName: 'Charlotte Galette',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'phima' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 108,
    cardName: 'Charlotte Cracker',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Misa Tsutsui', 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] If you have less Life cards than your opponent, this Character gains [Double Attack] and +1000 power.
    (This card deals 2 damage.)`,
    triggerText: `[Trigger] You may trash 1 card from your hand: Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 109,
    cardName: 'Charlotte Chiffon',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] You may trash 1 card from the top or bottom of your Life cards: Add up to 1 card from the top of your deck to the top of your Life cards.`,
  },{
    setId: SetId.OP03,
    setNumber: 110,
    cardName: 'Charlotte Smoothie',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'NIJIMAARC' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[When Attacking] You may add 1 card from the top or bottom of your Life cards to your hand: This Character gains +2000 power during this battle.`,
    triggerText: `[Trigger] You may trash 1 card from your hand: Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 111,
    cardName: 'Charlotte Praline',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hatori Kyoka' ],
    blockIcon: 1,
    types: [ TypeTags.Merfolk, TypeTags.TheSunPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 112,
    cardName: 'Charlotte Pudding',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hashimoto Q', 'Sunohara' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at 4 cards from the top of your deck; reveal up to 1 [Sanji] or {Big Mom Pirates} type card other than [Charlotte Pudding] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 113,
    cardName: 'Charlotte Pudding',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'DAI-XT.', 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On K.O.] Look at 3 cards from the top of your deck; reveal up to 1 {Big Mom Pirates} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP03,
    setNumber: 114,
    cardName: 'Charlotte Linlin',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Yosuke Adachi', 'Hayaken-sarena' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    cost: 10,
    power: 12000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] If your Leader has the {Big Mom Pirates} type, add up to 1 card from the top of your deck to the top of your Life cards. Then, trash up to 1 card from the top of your opponent's Life cards.`,
  },{
    setId: SetId.OP03,
    setNumber: 115,
    cardName: 'Streusen',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] You may trash 1 card with a [Trigger] from your hand: K.O. up to 1 of your opponent's Characters with a cost of 1 or less.`,
    counter: 2000,
  },{
    setId: SetId.OP03,
    setNumber: 116,
    cardName: 'Shirahoshi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'nuisuke' ],
    blockIcon: 1,
    types: [ TypeTags.Merfolk ],
    cost: 5,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Draw 3 cards and trash 2 cards from your hand.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 117,
    cardName: 'Napoleon',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] You may rest this Character: Up to 1 of your [Charlotte Linlin] cards gains +1000 power until the start of your next turn.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 118,
    cardName: 'Ikoku Sovereignty',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +5000 power during this battle.`,
    triggerText: `[Trigger] You may trash 2 cards from your hand: Add up to 1 card from the top of your deck to the top of your Life cards.`,
  },{
    setId: SetId.OP03,
    setNumber: 119,
    cardName: 'Buzz Cut Mochi',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 2,
    effectText: `[Main] If you have less Life cards than your opponent, K.O. up to 1 of your opponent's Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] Play up to 1 Character card with a cost of 4 or less and a [Trigger] from your hand.`,
  },{
    setId: SetId.OP03,
    setNumber: 120,
    cardName: 'Tropical Torment',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    effectText: `[Main] If your opponent has 4 or more Life cards, trash up to 1 card from the top of your opponent's Life cards.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP03,
    setNumber: 121,
    cardName: 'Thunder Bolt',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    cost: 2,
    effectText: `[Main] You may trash 1 card from the top of your Life cards: K.O. up to 1 of your opponent's Characters with a cost of 5 or less.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP03,
    setNumber: 122,
    cardName: 'Sogeking',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'Anime', 'Ryuda', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.SniperIsland ],
    cost: 7,
    power: 6000,
    attribute: CardAttribute.RANGED,
    effectText: `Also treat this card's name as [Usopp] according to the rules.
    [On Play] Return up to 1 Character with a cost of 6 or less to the owner's hand. Then, draw 2 cards and trash 2 cards from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP03,
    setNumber: 123,
    cardName: 'Charlotte Katakuri',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Studio Vigor Co.,Ltd', 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Add up to 1 Character with a cost of 8 or less to the top or bottom of the owner's Life cards face-up.`,
  },
];