import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.OP04,
    setNumber: 1,
    cardName: 'Nefeltari Vivi',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED, CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'phima' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `This Leader cannot attack.
    [Activate: Main] [Once Per Turn] ➁ (You may rest the specified number of DON!! cards in your cost area.): Draw 1 card and up to 1 of your Characters gains [Rush] during this turn.
    (This card can attack on the turn in which it is played.)`,
    life: 4,
  },{
    setId: SetId.OP04,
    setNumber: 2,
    cardName: 'Igaram',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Ryuda' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.RANGED,
    effectText: `[Activate: Main] You may rest this Character and give your 1 active Leader -5000 power during this turn: Look at 5 cards from the top of your deck; reveal up to 1 {Alabasta} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 3,
    cardName: 'Usopp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'TAPIOCA' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On K.O.] K.O. up to 1 of your opponent's Characters with 5000 base power or less.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 4,
    cardName: 'Karoo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.Alabasta ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] You may rest this Character: Give up to 1 rested DON!! card to each of your {Alabasta} type Characters.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 5,
    cardName: 'Kung Fu Jugon',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'SOWSOW' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.Alabasta ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.STRIKE,
    effectText: `If you have a [Kung Fu Jugon] other than this Character, this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 6,
    cardName: 'Koza',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Minato Sashima' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] You may give your 1 active Leader -5000 power during this turn: This Character gains +2000 power until the start of your next turn.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 7,
    cardName: 'Sanji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'otton' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 8,
    cardName: 'Chaka',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'KISUKE' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] If your Leader is [Nefeltari Vivi], give up to 1 of your opponent's Characters -3000 power during this turn. Then, K.O. up to 1 of your opponent's Characters with 0 power or less.`,
  },{
    setId: SetId.OP04,
    setNumber: 9,
    cardName: 'Super Spot-Billed Duck Troops',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'UGUME' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.Alabasta ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] You may give your 1 active Leader -5000 power during this turn: Return this Character to the owner's hand at the end of this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 10,
    cardName: 'Tony Tony.Chopper',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Play up to 1 {Animal} type Character card with 3000 power or less from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 11,
    cardName: 'Nami',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'NIJIMAARC' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[When Attacking] Reveal 1 card from the top of your deck. If the revealed card is a Character card with 6000 power or more, this Character gains +3000 power during this turn. Then, place the revealed card at the bottom of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 12,
    cardName: 'Nefeltari Cobra',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[Your Turn] All of your {Alabasta} type Characters other than this Character gain +1000 power.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 13,
    cardName: 'Pell',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Koushi Rokushiro', 'Denim2' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] K.O. up to 1 of your opponent's Characters with 4000 power or less.`,
  },{
    setId: SetId.OP04,
    setNumber: 14,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 8,
    power: 9000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Banish] (When this card deals damage, the target card is trashed without activating its Trigger.)`,
  },{
    setId: SetId.OP04,
    setNumber: 15,
    cardName: 'Roronoa Zoro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'AKIRA EGAWA' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Give up to 1 of your opponent's Characters -2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 16,
    cardName: 'Bad Manners Kick Course',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 0,
    effectText: `[Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.`,
    triggerText: `[Trigger] Give up to 1 of your opponent's Leader or Character cards -3000 power during this turn.`,
  },{
    setId: SetId.OP04,
    setNumber: 17,
    cardName: 'Happiness Punch',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta, TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Counter] Give up to 1 of your opponent's Leader or Character cards -2000 power during this turn. Then, if your Leader is active, give up to 1 of your opponent's Leader or Character cards -1000 power during this turn.`,
  },{
    setId: SetId.OP04,
    setNumber: 18,
    cardName: 'Enchanting Vertigo Dance',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    cost: 3,
    effectText: `[Main] If your Leader has the {Alabasta} type, give up to 2 of your opponent's Characters -2000 power during this turn.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP04,
    setNumber: 19,
    cardName: 'Donquixote Doflamingo',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ArtVariant.PARALLEL],
    artists: [ 'Anime', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[End of Your Turn] Set up to 2 of your DON!! cards as active.`,
    life: 4,
  },{
    setId: SetId.OP04,
    setNumber: 20,
    cardName: 'Issho',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ArtVariant.PARALLEL],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] [Your Turn] Give all of your opponent's Characters -1 cost.
    [End of Your Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): Set up to 1 of your Characters with a cost of 5 or less as active.`,
    life: 4,
  },{
    setId: SetId.OP04,
    setNumber: 21,
    cardName: 'Viola',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Your Opponent's Attack] ➁ (You may rest the specified number of DON!! cards in your cost area.): Rest up to 1 of your opponent's DON!! cards.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 22,
    cardName: 'Eric',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] You may rest this Character: Rest up to 1 of your opponent's Characters with a cost of 1 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 23,
    cardName: 'Kuro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Kaito Shibano' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.BlackCatPirates ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 24,
    cardName: 'Sugar',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Koushi Rokushiro', 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Opponent's Turn] [Once Per Turn] When your opponent plays a Character, if your Leader has the {Donquixote Pirates} type, rest up to 1 of your opponent's Characters. Then, rest this Character.
    [On Play] Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 25,
    cardName: 'Giolla',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Your Opponent's Attack] ➁ (You may rest the specified number of DON!! cards in your cost area.): Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 26,
    cardName: 'Senor Pink',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Hayaken-sarena' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[When Attacking] ➀ (You may rest the specified number of DON!! cards in your cost area.): If your Leader has the {Donquixote Pirates} type, rest up to 1 of your opponent's Characters with a cost of 4 or less. Then, set up to 1 of your DON!! cards as active at the end of this turn.`,
  },{
    setId: SetId.OP04,
    setNumber: 27,
    cardName: 'Daddy Masterson',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue, TypeTags.FormerNavy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[DON!! x1] [End of Your Turn] Set this Character as active.`,
  },{
    setId: SetId.OP04,
    setNumber: 28,
    cardName: 'Diamante',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'kankurou', 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [DON!! x1] [End of Your Turn] If you have 2 or more active DON!! cards, set this Character as active.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 29,
    cardName: 'Dellinger',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Yuu Shimotsuki' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[End of Your Turn] Set up to 1 of your DON!! cards as active.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 30,
    cardName: 'Trebol',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'kankurou', 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 6,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] K.O. up to 1 of your opponent's rested Characters with a cost of 5 or less.
    [On Your Opponent's Attack] ➁ (You may rest the specified number of DON!! cards in your cost area.): Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP04,
    setNumber: 31,
    cardName: 'Donquixote Doflamingo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'DAI-XT.', 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 10,
    power: 10000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Up to a total of 3 of your opponent's rested Leader and Character cards will not become active in your opponent's next Refresh Phase.`,
  },{
    setId: SetId.OP04,
    setNumber: 32,
    cardName: 'Baby 5',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Akira Kano' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[End of Your Turn] You may trash this Character: Set up to 2 of your DON!! cards as active.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 33,
    cardName: 'Machvise',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If your Leader has the {Donquixote Pirates} type, rest up to 1 of your opponent's Characters with a cost of 5 or less. Then, set up to 1 of your DON!! cards as active at the end of this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 34,
    cardName: 'Lao.G',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'touge369' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[End of Your Turn] If you have 3 or more active DON!! cards, K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 35,
    cardName: 'Spiderweb',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, set up to 1 of your Characters as active.`,
    triggerText: `[Trigger] Up to 1 of your Leader gains +2000 power during this turn.`,
  },{
    setId: SetId.OP04,
    setNumber: 36,
    cardName: 'Donquixote Family',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.DonquixotePirates ],
    cost: 1,
    effectText: `[Counter] Look at 5 cards from the top of your deck; reveal up to 1 {Donquixote Pirates} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Activate this card's [Counter] effect.`,
  },{
    setId: SetId.OP04,
    setNumber: 37,
    cardName: 'Flapping Thread',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 2,
    effectText: `[Counter] If your Leader has the {Donquixote Pirates} type, up to 1 of your Leader or Character cards gains +2000 power during this turn.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP04,
    setNumber: 38,
    cardName: 'The Weak Do Not Have the Right to Choose How They Die!!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 2,
    effectText: `[Main]/[Counter] Rest up to 1 of your opponent's Leader or Character cards. Then, K.O. up to 1 of your opponent's rested Characters with a cost of 6 or less.`,
    triggerText: `[Trigger] Set up to 5 of your DON!! cards as active.`,
  },{
    setId: SetId.OP04,
    setNumber: 39,
    cardName: 'Rebecca',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE, CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `This Leader cannot attack.
    [Activate: Main] [Once Per Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): If you have 6 or less cards in your hand, look at 2 cards from the top of your deck; reveal up to 1 {Dressrosa} type card and add it to your hand. Then, trash the rest.`,
    life: 5,
  },{
    setId: SetId.OP04,
    setNumber: 40,
    cardName: 'Queen',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE, CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[DON!! x1] [When Attacking] If you have a total of 4 or less cards in your Life area and hand, draw 1 card. If you have a Character with a cost of 8 or more, you may add up to 1 card from the top of your deck to the top of your Life cards instead of drawing 1 card.`,
    life: 4,
  },{
    setId: SetId.OP04,
    setNumber: 41,
    cardName: 'Apis',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] You may trash 2 cards from your hand: Look at 5 cards from the top of your deck; reveal up to 1 {East Blue} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 42,
    cardName: 'Ipponmatsu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Moopic' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Up to 1 of your <Slash> attribute Characters gains +3000 power during this turn. Then, trash 1 card from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 43,
    cardName: 'Ulti',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'tasaka' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [When Attacking] Return up to 1 Character with a cost of 2 or less to the owner's hand or the bottom of their deck.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 44,
    cardName: 'Kaido',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Mitsuaki Matsumoto', 'tatsuya' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 10,
    power: 12000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Return up to 1 Character with a cost of 8 or less and up to 1 Character with a cost of 3 or less to the owner's hand.`,
  },{
    setId: SetId.OP04,
    setNumber: 45,
    cardName: 'King',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Amano Yoichi' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 7,
    power: 8000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Draw 1 card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 46,
    cardName: 'Queen',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If your Leader has the {Animal Kingdom Pirates} type, look at 7 cards from the top of your deck; reveal a total of up to 2 [Plague Rounds] or [Ice Oni] cards and add them to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 47,
    cardName: 'Ice Oni',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'COGA' ],
    blockIcon: 1,
    types: [ TypeTags.Plague, TypeTags.AnimalKingdomPirates ],
    cost: 8,
    power: 0,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Your Turn] At the end of a battle in which this Character battles your opponent's Character with a cost of 5 or less, place the opponent's Character you battled with at the bottom of the owner's deck.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 48,
    cardName: 'Sasaki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Mitsuaki Matsumoto' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Return all cards in your hand to your deck and shuffle your deck. Then, draw cards equal to the number you returned to your deck.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 49,
    cardName: 'Jack',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'S-KINOKO' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On K.O.] Draw 1 card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 50,
    cardName: 'Hanger',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'COGA' ],
    blockIcon: 1,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may trash 1 card from your hand and rest this Character: Draw 1 card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 51,
    cardName: `Who's.Who`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Suzume Muraichi', 'nukadokomogera' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Animal Kingdom Pirates} type card other than [Who's.Who] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 52,
    cardName: `Black Maria`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Tanaka Kenichi' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] ➁ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character: Draw 1 card.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 53,
    cardName: `Page One`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'ASAKI KURODA' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [Once Per Turn] When you activate an Event, draw 1 card. Then, place 1 card from your hand at the bottom of your deck.`,
  },{
    setId: SetId.OP04,
    setNumber: 54,
    cardName: `Rokki`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'nukadokomogera' ],
    blockIcon: 1,
    types: [ TypeTags.Giant, TypeTags.AnimalKingdomPirates ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 55,
    cardName: `Plague Rounds`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 2,
    effectText: `[Main] You may trash 1 [Ice Oni] from your hand and place 1 Character with a cost of 4 or less at the bottom of the owner's deck: Play 1 [Ice Oni] from your trash.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP04,
    setNumber: 56,
    cardName: `Gum-Gum Red Roc`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 6,
    effectText: `[Main] Place up to 1 Character at the bottom of the owner's deck.`,
    triggerText: `[Trigger] Place up to 1 Character with a cost of 4 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP04,
    setNumber: 57,
    cardName: `Dragon Twister Demolition Breath`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, place up to 1 Character with a cost of 1 or less at the bottom of the owner's deck.`,
    triggerText: `[Trigger] Return up to 1 Character with a cost of 6 or less to the owner's hand.`,
  },{
    setId: SetId.OP04,
    setNumber: 58,
    cardName: `Crocodile`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.PURPLE, CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'tasaka' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Opponent's Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck by your effect, add up to 1 DON!! card from your DON!! deck and set it as active.`,
    life: 4,
  },{
    setId: SetId.OP04,
    setNumber: 59,
    cardName: `Iceburg`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hidano Kentaro' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.GalleyLa ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Your Opponent's Attack] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the {Water Seven} type, this Character gains [Blocker] during this turn.
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 60,
    cardName: `Crocodile`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'akagi', 'tatsuya' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    cost: 8,
    power: 9000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader's type includes "Baroque Works", add up to 1 card from the top of your deck to the top of your Life cards.
    [On Your Opponent's Attack] [Once Per Turn] DON!! -1: Draw 1 card and trash 1 card from your hand.`,
  },{
    setId: SetId.OP04,
    setNumber: 61,
    cardName: `Tom`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Moopic' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.WaterSeven ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may trash this Character: If your Leader has the {Water Seven} type, add up to 1 DON!! card from your DON!! deck and rest it.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 62,
    cardName: `Bananagator`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'S-KINOKO' ],
    blockIcon: 1,
    types: [ TypeTags.Animal ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 63,
    cardName: `Franky`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.WaterSeven, TypeTags.TheFrankyFamily ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Your Opponent's Attack] [Once Per Turn] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the {Water Seven} type, up to 1 of your Leader or Character cards gains +1000 power during this battle.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 64,
    cardName: `Ms. All Sunday`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Sunohara', 'Hatori Kyoka' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Add up to 1 DON!! card from your DON!! deck and rest it. Then, if you have 6 or more DON!! cards on your field, draw 1 card.`,
    triggerText: `[Trigger] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
  },{
    setId: SetId.OP04,
    setNumber: 64,
    cardName: `Ms. All Sunday`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Sunohara', 'Hatori Kyoka' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Add up to 1 DON!! card from your DON!! deck and rest it. Then, if you have 6 or more DON!! cards on your field, draw 1 card.`,
    triggerText: `[Trigger] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
  },{
    setId: SetId.OP04,
    setNumber: 65,
    cardName: `Miss.Goldenweek(Marianne)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Bashikou' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] If your Leader's type includes "Baroque Works", up to 1 of your opponent's Characters with a cost of 5 or less cannot attack until the start of your next turn.`,
    triggerText: `[Trigger] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 66,
    cardName: `Miss.Valentine(Mikita)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 card with a type including "Baroque Works" and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 67,
    cardName: `Miss.MerryChristmas(Drophy)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    triggerText: `[Trigger] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
  },{
    setId: SetId.OP04,
    setNumber: 68,
    cardName: `Yokozuna`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.WaterSeven ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Your Opponent's Attack] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Return up to 1 of your opponent's Characters with a cost of 2 or less to the owner's hand.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 69,
    cardName: `Mr.2.Bon.Kurei(Bentham)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'otton' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Your Opponent's Attack] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character's base power becomes the same as the power of your opponent's attacking Leader or Character during this turn.`,
    triggerText: `[Trigger] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 70,
    cardName: `Mr.3(Galdino)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Your Opponent's Attack] [Once Per Turn] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Give up to 1 of your opponent's Characters -1000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 71,
    cardName: `Mr.4(Babe)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anderson' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Your Opponent's Attack] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains [Blocker] and +1000 power during this battle.
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 72,
    cardName: `Mr.5(Gem)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hashimoto Q', 'Ryuda' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 7,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Your Opponent's Attack] [Once Per Turn] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may rest this Character: K.O. up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP04,
    setNumber: 73,
    cardName: `Mr.13 & Ms.Friday`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'SOWSOW' ],
    blockIcon: 1,
    types: [ TypeTags.Animal, TypeTags.BaroqueWorks ],
    cost: 3,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may trash this Character and 1 of your Characters with a type including "Baroque Works": Add up to 1 DON!! card from your DON!! deck and set it as active.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 74,
    cardName: `Colors Trap`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 1,
    effectText: `[Counter] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Up to 1 of your Leader or Character cards gains +1000 power during this battle. Then, rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP04,
    setNumber: 75,
    cardName: `Nez-Palm Cannon`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +6000 power during this battle. Then, if you have 2 or less Life cards, add up to 1 DON!! card from your DON!! deck and rest it.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP04,
    setNumber: 76,
    cardName: `Weakness...Is an Unforgivable Sin.`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BaroqueWorks ],
    cost: 1,
    effectText: `[Counter] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP04,
    setNumber: 77,
    cardName: `Ideo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Kawaguchi Yuki' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 78,
    cardName: `Oimo & Kashii`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'touge369' ],
    blockIcon: 1,
    types: [ TypeTags.Giant, TypeTags.WorldGovernment ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 79,
    cardName: `Orlumbus`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.YontaMariaFleet ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] [Once Per Turn] Give up to 1 of your opponent's Characters -4 cost during this turn and trash 2 cards from the top of your deck. Then, K.O. 1 of your {Dressrosa} type Characters.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 80,
    cardName: `Gyats`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Up to 1 of your {Dressrosa} type Characters can also attack active Characters during this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 81,
    cardName: `Cavendish`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.BeautifulPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] This Character can also attack active Characters.
    [When Attacking] You may rest your Leader: K.O. up to 1 of your opponent's Characters with a cost of 1 or less. Then, trash 2 cards from the top of your deck.`,
  },{
    setId: SetId.OP04,
    setNumber: 82,
    cardName: `Kyros`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'BISAI', 'DAI-XT.' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `If this Character would be K.O.'d, you may rest your Leader or 1 [Corrida Coliseum] instead.
    [On Play] If your Leader is [Rebecca], K.O. up to 1 of your opponent's Characters with a cost of 1 or less. Then, trash 1 card from the top of your deck.`,
  },{
    setId: SetId.OP04,
    setNumber: 83,
    cardName: `Sabo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'BISAI', 'Manga', 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.RevolutionaryArmy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] None of your Characters can be K.O.'d by effects until the start of your next turn. Then, draw 2 cards and trash 2 cards from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 84,
    cardName: `Stussy`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Yamamoto Ryohei' ],
    blockIcon: 1,
    types: [ TypeTags.CP0 ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Look at 3 cards from the top of your deck and play up to 1 Character card with a type including "CP" other than [Stussy] and a cost of 2 or less. Then, trash the rest.`,
  },{
    setId: SetId.OP04,
    setNumber: 85,
    cardName: `Suleiman`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Amano Yoichi' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play]/[When Attacking] If your Leader has the {Dressrosa} type, give up to 1 of your opponent's Characters -2 cost during this turn. Then, trash 1 card from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 86,
    cardName: `Chinjao`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hidano Kentaro' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.HapposuiArmy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] When this Character battles and K.O.'s your opponent's Character, draw 2 cards and trash 2 cards from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 87,
    cardName: `Trafalgar Law`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.HeartPirates ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 88,
    cardName: `Hajrudin`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Giant, TypeTags.Dressrosa, TypeTags.NewGiantPirates ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] You may rest your 1 Leader: Give up to 1 of your opponent's Characters -4 cost during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 89,
    cardName: `Bartolomeo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.BartoClub ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 90,
    cardName: `Monkey.D.Luffy`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Yuu Shimotsuki', 'Hokuyuu' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.StrawHatCrew ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `This Character can also attack active Characters.
    [Activate: Main] [Once Per Turn] You may return 7 cards from your trash to the bottom of your deck in any order: Set this Character as active. Then, this Character will not become active in your next Refresh Phase.`,
  },{
    setId: SetId.OP04,
    setNumber: 91,
    cardName: `Leo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Yuu Shimotsuki' ],
    blockIcon: 1,
    types: [ TypeTags.TheTontattas, TypeTags.Dressrosa ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] You may rest your 1 Leader: If your Leader has the {Dressrosa} type, K.O. up to 1 of your opponent's Characters with a cost of 1 or less. Then, trash 2 cards from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 92,
    cardName: `Rebecca`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Hokuyuu' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Look at 3 cards from the top of your deck; reveal up to 1 {Dressrosa} type card other than [Rebecca] and add it to your hand. Then, trash the rest.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 93,
    cardName: `Gum-Gum King Kong Gun`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.StrawHatCrew ],
    cost: 3,
    effectText: `[Main] Up to 1 of your {Dressrosa} type Characters gains +6000 power during this turn. Then, if you have 15 or more cards in your trash, that card gains [Double Attack] during this turn.
    (This card deals 2 damage.)`,
    triggerText: `[Trigger] Draw 3 cards and trash 2 cards from your hand.`,
  },{
    setId: SetId.OP04,
    setNumber: 94,
    cardName: `Trueno Bastardo`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 4,
    effectText: `[Main] Choose up to 1 of your opponent's Characters with a cost of 4 or less and K.O. it. If you have 15 or more cards in your trash, choose up to 1 of your opponent's Characters with a cost of 6 or less instead of a Character with a cost of 4 or less.`,
    triggerText: `[Trigger] You may rest your Leader: K.O. up to 1 of your opponent's Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP04,
    setNumber: 95,
    cardName: `Barrier!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa, TypeTags.BartoClub ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 15 or more cards in your trash, that card gains an additional +2000 power during this battle.`,
    triggerText: `[Trigger] Draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.OP04,
    setNumber: 96,
    cardName: `Corrida Coliseum`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Dressrosa ],
    cost: 1,
    effectText: `If your Leader has the {Dressrosa} type, your {Dressrosa} type Characters can attack Characters on the turn in which they are played.`,
  },{
    setId: SetId.OP04,
    setNumber: 97,
    cardName: `Otama`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Add up to 1 of your opponent's {Animal} or {SMILE} type Characters with a cost of 3 or less to the top of your opponent's Life cards face-up.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 98,
    cardName: `Toko`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] You may trash 2 {Land of Wano} type cards from your hand: If you have 1 or less Life cards, add 1 card from the top of your deck to the top of your Life cards.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 99,
    cardName: `Olin`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `Also treat this card's name as [Charlotte Linlin] according to the rules.`,
    triggerText: `[Trigger] If you have 1 or less Life cards, play this card.`,
  },{
    setId: SetId.OP04,
    setNumber: 100,
    cardName: `Capone"Gang"Bege`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'HISASHI HUJIWARA', 'Hayaken-sarena' ],
    blockIcon: 1,
    types: [ TypeTags.FiretankPirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.RANGED,
    triggerText: `[Trigger] Up to 1 of your opponent's Leader or Character cards cannot attack during this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 101,
    cardName: `Carmel`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.TheHouseOfLambs ],
    cost: 2,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Your Turn] [On Play] Draw 1 card.`,
    triggerText: `[Trigger] Play this card. Then, K.O. up to 1 of your opponent's Characters with a cost of 2 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 102,
    cardName: `Kin'emon`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'DAI-XT.' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 6,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may add 1 card from the top or bottom of your Life cards to your hand: Set this Character as active.`,
  },{
    setId: SetId.OP04,
    setNumber: 103,
    cardName: `Kouzuki Hiyori`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Up to 1 of your {Land of Wano} type Leader or Character cards gains +1000 power during this turn.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 104,
    cardName: `Sanji`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hayaken-sarena', 'Daisuke Izuka' ],
    blockIcon: 1,
    types: [ TypeTags.TheVinsmokeFamily ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    triggerText: `[Trigger] You may trash 1 card from your hand: Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 105,
    cardName: `Charlotte Amande`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] You may trash 1 card with a [Trigger] from your hand: Rest up to 1 of your opponent's Characters with a cost of 2 or less.`,
    counter: 2000,
  },{
    setId: SetId.OP04,
    setNumber: 106,
    cardName: `Charlotte Bavarois`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] If you have less Life cards than your opponent, this Character gains +1000 power.`,
    triggerText: `[Trigger] You may trash 1 card from your hand: Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 107,
    cardName: `Charlotte Perospero`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 108,
    cardName: `Charlotte Moscato`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] This Character gains [Banish].
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
    triggerText: `[Trigger] You may trash 1 card from your hand: Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 109,
    cardName: `Tonoyasu`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may trash this Character: Up to 1 of your {Land of Wano} type Leader or Character cards gains +3000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 110,
    cardName: `Pound`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.WholeCakeIsland ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] Add up to 1 of your opponent's Characters with a cost of 3 or less to the top or bottom of your opponent's Life cards face-up.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 111,
    cardName: `Hera`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 5,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] You may trash 1 of your {Homies} type Characters other than this Character and rest this Character: Set up to 1 of your [Charlotte Linlin] Characters as active.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 112,
    cardName: `Yamato`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Kaito Shibano', 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 9,
    power: 9000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] K.O. up to 1 of your opponent's Characters with a cost equal to or less than the total of your and your opponent's Life cards. Then, if you have 1 or less Life cards, add up to 1 card from the top of your deck to the top of your Life cards.`,
  },{
    setId: SetId.OP04,
    setNumber: 113,
    cardName: `Rabiyan`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 114,
    cardName: `Randolph`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'shosuke' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 115,
    cardName: `Gun Modoki`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    effectText: `[Main] You may add 1 card from the top or bottom of your Life cards to your hand: Up to 1 of your {Land of Wano} type Characters gains [Double Attack] during this turn.
    (This card deals 2 damage.)`,
    triggerText: `[Trigger] Up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
  },{
    setId: SetId.OP04,
    setNumber: 116,
    cardName: `Diable Jambe Joue Shot`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheVinsmokeFamily ],
    cost: 3,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +6000 power during this battle. Then, if you and your opponent have a total of 4 or less Life cards, K.O. up to 1 of your opponent's Characters with a cost of 2 or less.`,
    triggerText: `[Trigger] Draw 1 card.`,
  },{
    setId: SetId.OP04,
    setNumber: 117,
    cardName: `Heavenly Fire`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    cost: 1,
    effectText: `[Main] Add up to 1 of your opponent's Characters with a cost of 3 or less to the top or bottom of your opponent's Life cards face-up.`,
    triggerText: `[Trigger] You may add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 card from your hand to the top of your Life cards.`,
  },{
    setId: SetId.OP04,
    setNumber: 118,
    cardName: `Nefeltari Vivi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hatori Kyoka', 'SHIE NANAHARA' ],
    blockIcon: 1,
    types: [ TypeTags.Alabasta ],
    cost: 7,
    power: 4000,
    attribute: CardAttribute.WISDOM,
    effectText: `All of your red Characters with a cost of 3 or more other than this Character gain [Rush].
    (This card can attack on the turn in which it is played.)`,
    counter: 1000,
  },{
    setId: SetId.OP04,
    setNumber: 119,
    cardName: `Donquixote Rosinante`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'BISAI', 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.Navy, TypeTags.DonquixotePirates ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Opponent's Turn] If this Character is rested, your active Characters with a base cost of 5 cannot be K.O.'d by effects.
    [On Play] You may rest this Character: Play up to 1 green Character card with a cost of 5 from your hand.`,
  },
];
