import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.OP05,
    setNumber: 1,
    cardName: 'Sabo',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED, CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] [Opponent's Turn] [Once Per Turn] If your Character with 5000 power or more would be K.O.'d, you may give that Character -1000 power during this turn instead of that Character being K.O.'d.`,
    life: 4,
  },{
    setId: SetId.OP05,
    setNumber: 2,
    cardName: 'Belo Betty',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED, CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] You may trash 1 {Revolutionary Army} type card from your hand: Up to 3 of your {Revolutionary Army} type Characters or Characters with a [Trigger] gain +3000 power during this turn.`,
    life: 4,
  },{
    setId: SetId.OP05,
    setNumber: 3,
    cardName: 'Inazuma',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `If you have a Character with 7000 power or more other than this Character, this Character gains [Rush].
    (This card can attack on the turn in which it is played.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 4,
    cardName: 'Emporio.Ivankov',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'ASAKI KURODA' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] If this Character has 7000 power or more, play up to 1 {Revolutionary Army} type Character card with 5000 power or less other than [Emporio.Ivankov] from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 5,
    cardName: 'Karasu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'ASAKI KURODA' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] If your Leader has the {Revolutionary Army} type, give up to 1 of your opponent's Leader or Character cards -1000 power during this turn.
    [When Attacking] If this Character has 7000 power or more, give up to 1 of your opponent's Leader or Character cards -1000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 6,
    cardName: 'Koala',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'aosora', 'Hatori Kyoka' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If your Leader has the {Revolutionary Army} type, give up to 1 of your opponent's Characters -3000 power during this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 7,
    cardName: 'Sabo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'tasaka', 'Sunohara' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] K.O. up to 2 of your opponent's Characters with a total power of 4000 or less.`,
  },{
    setId: SetId.OP05,
    setNumber: 8,
    cardName: 'Chaka',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Tanaka Kenichi' ],
    blockIcon: 2,
    types: [ TypeTags.Alabasta ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [Activate: Main] [Once Per Turn] Give up to 2 rested DON!! cards to your Leader or 1 of your Characters.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 9,
    cardName: 'Toh-Toh',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Moopic' ],
    blockIcon: 2,
    types: [ TypeTags.Alabasta ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Draw 1 card if your Leader has 0 power or less.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 10,
    cardName: 'Nico Robin',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] K.O. up to 1 of your opponent's Characters with 1000 power or less.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 11,
    cardName: 'Bartholomew Kuma',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.RevolutionaryArmy ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] K.O. up to 1 of your opponent's Characters with 2000 power or less.`,
    triggerText: `[Trigger] If your Leader is multicolored, play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 12,
    cardName: 'Hack',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.RevolutionaryArmy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 13,
    cardName: 'Bunny Joe',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'COGA' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.RANGED,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 14,
    cardName: 'Pell',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.Alabasta ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] Give up to 1 of your opponent's Characters -2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 15,
    cardName: 'Belo Betty',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hatori Kyoka', 'phima' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Revolutionary Army} type card other than [Belo Betty] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 16,
    cardName: 'Morley',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'ASAKI KURODA' ],
    blockIcon: 2,
    types: [ TypeTags.Giant, TypeTags.RevolutionaryArmy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[When Attacking] If this Character has 7000 power or more, your opponent cannot activate [Blocker] during this battle.`,
    triggerText: `[Trigger] You may trash 1 card from your hand: If your Leader is multicolored, play this card.`,
  },{
    setId: SetId.OP05,
    setNumber: 17,
    cardName: 'Lindbergh',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 2,
    types: [ TypeTags.Minks, TypeTags.RevolutionaryArmy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[When Attacking] If this Character has 7000 power or more, K.O. up to 1 of your opponent's Characters with 3000 power or less.`,
    triggerText: `[Trigger] You may trash 1 card from your hand: If your Leader is multicolored, play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 18,
    cardName: 'Emporio Energy Hormone',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 3,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +3000 power during this battle. Then, play up to 1 {Revolutionary Army} type Character card with 5000 power or less from your hand.`,
    triggerText: `[Trigger] Play up to 1 {Revolutionary Army} type Character card with 5000 power or less from your hand.`,
  },{
    setId: SetId.OP05,
    setNumber: 19,
    cardName: 'Fire Fist',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 2,
    effectText: `[Main] Give up to 1 of your opponent's Characters -4000 power during this turn. Then, if you have 2 or less Life cards, K.O. up to 1 of your opponent's Characters with 0 power or less.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP05,
    setNumber: 20,
    cardName: 'Four Thousand-Brick Fist',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.RevolutionaryArmy ],
    cost: 2,
    effectText: `[Main] Up to 1 of your Leader or Character cards gains +2000 power during this turn. Then, K.O. up to 1 of your opponent's Characters with 2000 power or less.`,
    triggerText: `[Trigger] Up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
  },{
    setId: SetId.OP05,
    setNumber: 21,
    cardName: 'Revolutionary Army HQ',
    cardType: CardType.STAGE,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 1,
    effectText: `[Activate: Main] You may trash 1 card from your hand and rest this Stage: Look at 3 cards from the top of your deck; reveal up to 1 {Revolutionary Army} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP05,
    setNumber: 22,
    cardName: 'Donquixote Rosinante',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Navy, TypeTags.DonquixotePirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [End of Your Turn] If you have 6 or less cards in your hand, set this Leader as active.`,
    life: 4,
  },{
    setId: SetId.OP05,
    setNumber: 23,
    cardName: 'Vergo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Daiki Ihara' ],
    blockIcon: 2,
    types: [ TypeTags.Navy, TypeTags.DonquixotePirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [When Attacking] K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 24,
    cardName: 'Kuween',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 25,
    cardName: 'Gladius',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Morechand' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] You may rest this Character: Rest up to 1 of your opponent's Characters with a cost of 3 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 26,
    cardName: 'Sarquiss',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 2,
    types: [ TypeTags.BellamyPirates ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] [Once Per Turn] You may rest 1 of your Characters with a cost of 3 or more: Set this Character as active.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 27,
    cardName: 'Trafalgar Law',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may trash this Character: Rest up to 1 of your opponent's Characters with a cost of 3 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 28,
    cardName: 'Donquixote Doflamingo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.RANGED,
    effectText: `[Activate: Main] You may trash this Character: K.O. up to 1 of your opponent's rested Characters with a cost of 2 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 29,
    cardName: 'Donquixote Doflamingo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nijihayashi' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 7,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Your Opponent's Attack] [Once Per Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): Rest up to 1 of your opponent's Characters with a cost of 6 or less.`,
  },{
    setId: SetId.OP05,
    setNumber: 30,
    cardName: 'Donquixote Rosinante',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Nijihayashi' ],
    blockIcon: 2,
    types: [ TypeTags.Navy, TypeTags.DonquixotePirates ],
    cost: 2,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [Opponent's Turn] If your rested Character would be K.O.'d, you may trash this Character instead.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 31,
    cardName: 'Buffalo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] [Once Per Turn] If you have 2 or more rested Characters, set up to 1 of your rested Characters with a cost of 1 as active.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 32,
    cardName: 'Pica',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Kentaro Hidano', 'DAI-XT.' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[End of Your Turn] ①: Set this Character as active.
    [Once Per Turn] If this Character would be K.O.'d, you may rest up to 1 of your Characters with a cost of 3 or more other than [Pica] instead.`,
  },{
    setId: SetId.OP05,
    setNumber: 33,
    cardName: 'Baby 5',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character: Play up to 1 {Donquixote Pirates} type Character card with a cost of 2 or less from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 34,
    cardName: 'Baby 5',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Koushi Rokushiro', 'Hagane Tsurugi' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character: Look at 5 cards from the top of your deck; reveal up to 1 {Donquixote Pirates} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP05,
    setNumber: 35,
    cardName: 'Baby 5',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'BISAI' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 36,
    cardName: 'Monet',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'BISAI' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 3,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Block] Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 37,
    cardName: 'Because the Side of Justice Will Be Whichever Side Wins!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 0,
    effectText: `[Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.`,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP05,
    setNumber: 38,
    cardName: 'Charlestone',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, you may trash 1 card from your hand. If you do, set up to 3 of your DON!! cards as active.`,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Leader or Character cards with a cost of 3 or less.`,
  },{
    setId: SetId.OP05,
    setNumber: 39,
    cardName: 'Stick-Stickem Meteora',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's rested Characters with a cost of 5 or less.`,
  },{
    setId: SetId.OP05,
    setNumber: 40,
    cardName: 'Birdcage',
    cardType: CardType.STAGE,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.DonquixotePirates ],
    cost: 5,
    effectText: `If your Leader is [Donquixote Doflamingo], all Characters with a cost of 5 or less do not become active in your and your opponent's Refresh Phases.
    [End of Your Turn] If you have 10 DON!! cards on your field, K.O. all rested Characters with a cost of 5 or less. Then, trash this Stage.`,
  },{
    setId: SetId.OP05,
    setNumber: 41,
    cardName: 'Sakazuki',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE, CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] You may trash 1 card from your hand: Draw 1 card.
    [When Attacking] Give up to 1 of your opponent's Characters -1 cost during this turn.`,
    life: 4,
  },{
    setId: SetId.OP05,
    setNumber: 42,
    cardName: 'Issho',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Kentaro Hidano' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 6,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Up to 1 of your opponent's Characters with a cost of 7 or less cannot attack until the start of your next turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 43,
    cardName: 'Ulti',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hokuyuu', 'Akira Kano' ],
    blockIcon: 2,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If your Leader is multicolored, look at 3 cards from the top of your deck and add up to 1 card to your hand. Then, place the rest at the top or bottom of the deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 44,
    cardName: 'John Giant',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nakamaru' ],
    blockIcon: 2,
    types: [ TypeTags.Giant, TypeTags.Navy ],
    cost: 8,
    power: 10000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 45,
    cardName: 'Stainless',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] You may trash 1 card from your hand and rest this Character: Place up to 1 Character with a cost of 2 or less at the bottom of the owner's deck.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 46,
    cardName: 'Dalmatian',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On K.O.] Draw 1 card and place 1 card from your hand at the bottom of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 47,
    cardName: 'Basil Hawkins',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'eiji kaneda' ],
    blockIcon: 2,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.HawkinsPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Block] Draw 1 card if you have 3 or less cards in your hand. Then, this Character gains +1000 power during this battle.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 48,
    cardName: 'Bastille',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] Place up to 1 Character with a cost of 2 or less at the bottom of the owner's deck.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 49,
    cardName: 'Haccha',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'touge369' ],
    blockIcon: 2,
    types: [ TypeTags.Giant, TypeTags.AnimalKingdomPirates ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [When Attacking] Return up to 1 Character with a cost of 3 or less to the owner's hand.`,
  },{
    setId: SetId.OP05,
    setNumber: 50,
    cardName: 'Hina',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Tadahiro Miura' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Draw 1 card if you have 5 or less cards in your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 51,
    cardName: 'Borsalino',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'DAI-XT.', 'Hayaken-sarena' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 7,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Place up to 1 Character with a cost of 4 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP05,
    setNumber: 52,
    cardName: 'Maynard',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 53,
    cardName: 'Mozambia',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[Your Turn] [Once Per Turn] When you draw a card outside of your Draw Phase, this Character gains +2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 54,
    cardName: 'Monkey.D.Garp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nekamaru' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Draw 2 cards and place 2 cards from your hand at the bottom of your deck in any order.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 55,
    cardName: 'X.Drake',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Kentaro Hidano', 'Hokuyuu' ],
    blockIcon: 2,
    types: [ TypeTags.Navy, TypeTags.DrakePirates, TypeTags.AnimalKingdomPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] Look at 5 cards from the top of your deck and place them at the top or bottom of the deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 56,
    cardName: 'X.Barrels',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hokuyuu' ],
    blockIcon: 2,
    types: [ TypeTags.FormerNavy ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] You may place 1 of your Characters other than this Character at the bottom of your deck: Draw 1 card.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 57,
    cardName: 'Hound Blaze',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 2,
    effectText: `[Main] Up to 1 of your Leader or Character cards gains +3000 power during this turn. Then, place up to 1 Character with a cost of 2 or less at the bottom of the owner's deck.`,
    triggerText: `[Trigger] Return up to 1 Character with a cost of 3 or less to the owner's hand.`,
  },{
    setId: SetId.OP05,
    setNumber: 58,
    cardName: `It's a Waste of Human Life!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 8,
    effectText: `[Main] Place all Characters with a cost of 3 or less at the bottom of the owner's deck. Then, you and your opponent trash cards from your hands until you each have 5 cards in your hands.`,
    triggerText: `[Trigger] Place all Characters with a cost of 2 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP05,
    setNumber: 59,
    cardName: `Let Us Begin the World of Violence!!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 5,
    effectText: `[Main] If your Leader is multicolored, draw 1 card. Then, return up to 1 Character with a cost of 5 or less to the owner's hand.`,
    triggerText: `[Trigger] If your Leader is multicolored, draw 2 cards.`,
  },{
    setId: SetId.OP05,
    setNumber: 60,
    cardName: `Monkey.D.Luffy`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] [Once Per Turn] You may add 1 card from the top of your Life cards to your hand: If you have 0 or 3 or more DON!! cards on your field, add up to 1 DON!! card from your DON!! deck and set it as active.`,
    life: 5,
  },{
    setId: SetId.OP05,
    setNumber: 61,
    cardName: `Uso-Hachi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.RANGED,
    effectText: `[DON!! x1] [When Attacking] If you have 8 or more DON!! cards on your field, rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 62,
    cardName: `O-Nami`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'SHIE NANAHARA' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `If you have 10 DON!! cards on your field, this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 63,
    cardName: `O-Robi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Sunohara' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If you have 8 or more DON!! cards on your field, K.O. up to 1 of your opponent's Characters with a cost of 3 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 64,
    cardName: `Killer`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'tatsuya' ],
    blockIcon: 2,
    types: [ TypeTags.KidPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Kid Pirates} type card other than [Killer] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 65,
    cardName: `San-Gorou`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'tatsuya' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 66,
    cardName: `Jinbe`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'nukadokomogera' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.StrawHatCrew ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [Opponent's Turn] If you have 10 DON!! cards on your field, this Character gains +1000 power.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 67,
    cardName: `Zoro-Juurou`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'tatsuya', 'Makitoshi' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] If you have 3 or less Life cards, add up to 1 DON!! card from your DON!! deck and set it as active.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 68,
    cardName: `Chopa-Emon`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 2,
    types: [ TypeTags.Animal, TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] If you have 8 or more DON!! cards on your field, set up to 1 of your purple {Straw Hat Crew} type Characters with 6000 power or less as active.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 69,
    cardName: `Trafalgar Law`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'Minato Sashima', 'AKIRA EGAWA', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.HeartPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] If your opponent has more DON!! cards on their field than you, look at 5 cards from the top of your deck; reveal up to 1 {Heart Pirates} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP05,
    setNumber: 70,
    cardName: `Fra-Nosuke`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 5,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] If you have 8 or more DON!! cards on your field, this Character gains [Rush].
    (This card can attack on the turn in which it is played.)`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 71,
    cardName: `Bepo`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'UGUME' ],
    blockIcon: 2,
    types: [ TypeTags.Minks, TypeTags.HeartPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] If your opponent has more DON!! cards on their field than you, give up to 1 of your opponent's Characters -2000 power during this turn.`,
  },{
    setId: SetId.OP05,
    setNumber: 72,
    cardName: `Hone-Kichi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If you have 8 or more DON!! cards on your field, give up to 2 of your opponent's Characters -2000 power during this turn.`,
  },{
    setId: SetId.OP05,
    setNumber: 73,
    cardName: `Miss Doublefinger(Zala)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 2,
    types: [ TypeTags.BaroqueWorks ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] You may trash 1 card from your hand: Add up to 1 DON!! card from your DON!! deck and rest it.`,
    triggerText: `[Trigger] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play this card.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 74,
    cardName: `Eustass"Captain"Kid`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'tatsuya', 'NIJIMAARC', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.KidPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker]
    [Your Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck, add up to 1 DON!! card from your DON!! deck and set it as active.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 75,
    cardName: `Mr.1(Daz.Bonez)`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'tasaka' ],
    blockIcon: 2,
    types: [ TypeTags.BaroqueWorks ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Your Opponent's Attack] [Once Per Turn] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play up to 1 {Baroque Works} type Character card with a cost of 3 or less from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 76,
    cardName: `When You're at Sea You Fight against Pirates!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano ],
    cost: 1,
    effectText: `[Main] Look at 3 cards from the top of your deck; reveal up to 1 {Straw Hat Crew}, {Kid Pirates}, or {Heart Pirates} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP05,
    setNumber: 77,
    cardName: `Gamma Knife`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.HeartPirates ],
    cost: 2,
    effectText: `[Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Give up to 1 of your opponent's Characters -5000 power during this turn.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP05,
    setNumber: 78,
    cardName: `Punk Rotten`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.KidPirates ],
    cost: 2,
    effectText: `[Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Up to 1 of your {Kid Pirates} type Leader or Character cards gains +5000 power during this turn.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.OP05,
    setNumber: 79,
    cardName: `Viola`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Bashikou' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Your opponent places 3 cards from their trash at the bottom of their deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 80,
    cardName: `Elizabello II`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'tasaka' ],
    blockIcon: 2,
    types: [ TypeTags.KingdomOfProdence ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] [Once Per Turn] You may return 20 cards from your trash to your deck and shuffle it: This Character gains [Double Attack] and +10000 power during this battle.
    (This card deals 2 damage.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 81,
    cardName: `One-Legged Toy Soldier`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Moopic' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] You may trash this Character: Give up to 1 of your opponent's Characters -3 cost during this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 82,
    cardName: `Shirahoshi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Hatori Kyoka' ],
    blockIcon: 2,
    types: [ TypeTags.Merfolk ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may rest this Character and place 2 cards from your trash at the bottom of your deck in any order: If your opponent has 6 or more cards in their hand, your opponent trashes 1 card from their hand.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 83,
    cardName: `Sterry`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 2,
    types: [ TypeTags.GoaKingdom ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 84,
    cardName: `Saint Charlos`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.CelestialDragons ],
    cost: 3,
    power: 0,
    attribute: CardAttribute.RANGED,
    effectText: `[Your Turn] If the only Characters on your field are {Celestial Dragons} type Characters, give all of your opponent's Characters -4 cost.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 85,
    cardName: `Nefeltari Cobra`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 2,
    types: [ TypeTags.Alabasta ],
    cost: 2,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] Trash 1 card from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 86,
    cardName: `Nefeltari Vivi`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'yuu' ],
    blockIcon: 2,
    types: [ TypeTags.Alabasta ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `If you have 10 or more cards in your trash, this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 87,
    cardName: `Hakuba`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'otton' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa, TypeTags.BeautifulPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] You may K.O. 1 of your Characters other than this Character: Give up to 1 of your opponent's Characters -5 cost during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 88,
    cardName: `Mansherry`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Suzume Muraichi', 'SOWSOW' ],
    blockIcon: 2,
    types: [ TypeTags.TheTontattas, TypeTags.Dressrosa ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character and place 2 cards from your trash at the bottom of your deck in any order: Add up to 1 black Character card with a cost of 3 to 5 from your trash to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 89,
    cardName: `Saint Mjosgard`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.CelestialDragons ],
    cost: 5,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Character and 1 of your Characters: Add up to 1 black Character card with a cost of 1 from your trash to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 90,
    cardName: `Riku Doldo III`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play]/[On K.O.] Up to 1 of your {Dressrosa} type Characters gains +2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 91,
    cardName: `Rebecca`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'POKImari', 'Makitoshi' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa ],
    cost: 4,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker]
    [On Play] Add up to 1 black Character card with a cost of 3 to 7 other than [Rebecca] from your trash to your hand. Then, play up to 1 black Character card with a cost of 3 or less from your hand rested.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 92,
    cardName: `Saint Rosward`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.CelestialDragons ],
    cost: 5,
    power: 0,
    attribute: CardAttribute.RANGED,
    effectText: `[Your Turn] If the only Characters on your field are {Celestial Dragons} type Characters, give all of your opponent's Characters -6 cost.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 93,
    cardName: `Rob Lucci`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'otton', 'Hashimoto Q' ],
    blockIcon: 2,
    types: [ TypeTags.CP0 ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] You may place 3 cards from your trash at the bottom of your deck in any order: K.O. up to 1 of your opponent's Characters with a cost of 2 or less and up to 1 of your opponent's Characters with a cost of 1 or less.`,
  },{
    setId: SetId.OP05,
    setNumber: 94,
    cardName: `Haute Couture Patch★Work`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.TheTontattas, TypeTags.Dressrosa ],
    cost: 1,
    effectText: `[Main] Give up to 1 of your opponent's Characters -3 cost during this turn. Then, up to 1 of your opponent's Characters with a cost of 0 will not become active in the next Refresh Phase.`,
    triggerText: `[Trigger] Draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.OP05,
    setNumber: 95,
    cardName: `Dragon Claw`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa, TypeTags.RevolutionaryArmy ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 15 or more cards in your trash, K.O. up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP05,
    setNumber: 96,
    cardName: `I Bid 500 Million!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.CelestialDragons ],
    cost: 3,
    effectText: `[Main] Choose one:
    • K.O. up to 1 of your opponent's Characters with a cost of 1 or less.
    • Return up to 1 of your opponent's Characters with a cost of 1 or less to the owner's hand.
    • Place up to 1 of your opponent's Characters with a cost of 1 or less at the top or bottom of their Life cards face-up.
    Then, if you have a {Celestial Dragons} type Character, draw 1 card.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 6 or less, or return it to the owner's hand.`,
  },{
    setId: SetId.OP05,
    setNumber: 97,
    cardName: `Mary Geoise`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.MaryGeoise ],
    cost: 1,
    effectText: `[Your Turn] The cost of playing {Celestial Dragons} type Character cards with a cost of 2 or more from your hand will be reduced by 1.`,
  },{
    setId: SetId.OP05,
    setNumber: 98,
    cardName: `Enel`,
    cardType: CardType.LEADER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Opponent's Turn] [Once Per Turn] When your number of Life cards becomes 0, add 1 card from the top of your deck to the top of your Life cards. Then, trash 1 card from your hand.`,
    life: 4,
  },{
    setId: SetId.OP05,
    setNumber: 99,
    cardName: `Amazon`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 3,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Your Opponent's Attack] You may rest this Character: Your opponent may trash 1 card from the top of their Life cards. If they do not, give up to 1 of your opponent's Leader or Character cards -2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 100,
    cardName: `Enel`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hokuyuu', 'Yosuke Adachi' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Rush]
    [Once Per Turn] If this Character would leave the field, you may trash 1 card from the top of your Life cards instead. If there is a [Monkey.D.Luffy] Character, this effect is negated.`,
  },{
    setId: SetId.OP05,
    setNumber: 101,
    cardName: `Ohm`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Morechand' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.Vassals ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `If you have 2 or less Life cards, this Character gains +1000 power.
    [On Play] Look at 5 cards from the top of your deck; reveal up to 1 [Holly] and add it to your hand. Then, place the rest at the bottom of your deck in any order and play up to 1 [Holly] from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 102,
    cardName: `Gedatsu`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Nekobayashi', 'DAI-XT.' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.Vassals ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] K.O. up to 1 of your opponent's Characters with a cost equal to or less than the number of your opponent's Life cards.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 103,
    cardName: `Kotori`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] If you have [Hotori], K.O. up to 1 of your opponent's Characters with a cost equal to or less than the number of your opponent's Life cards.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 104,
    cardName: `Conis`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] You may place 1 of your Stages at the bottom of your deck: Draw 1 card and trash 1 card from your hand.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 105,
    cardName: `Satori`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.Vassals ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    triggerText: `[Trigger] You may trash 1 card from your hand: Play this card.`,
    counter: 2000,
  },{
    setId: SetId.OP05,
    setNumber: 106,
    cardName: `Shura`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Daiki Ihara' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.Vassals ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Sky Island} type card other than [Shura] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 107,
    cardName: `Lieutenant Spacey`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'kito' ],
    blockIcon: 2,
    types: [ TypeTags.TheMoon ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.RANGED,
    effectText: `[Your Turn] [Once Per Turn] When a card is added to your hand from your Life, this Character gains +2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 108,
    cardName: `Nola`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'shosuke' ],
    blockIcon: 2,
    types: [ TypeTags.Animal, TypeTags.SkyIsland ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 109,
    cardName: `Pagaya`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Once Per Turn] When a [Trigger] activates, draw 2 cards and trash 2 cards from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 110,
    cardName: `Holly`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.Animal, TypeTags.SkyIsland ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 111,
    cardName: `Hotori`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] You may play 1 [Kotori] from your hand: Add up to 1 of your opponent's Characters with a cost of 3 or less to the top or bottom of your opponent's Life cards face-up.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 112,
    cardName: `Captain McKinley`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'touge369' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On K.O.] Play up to 1 {Sky Island} type Character card with a cost of 1 from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 113,
    cardName: `Yama`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP05,
    setNumber: 114,
    cardName: `El Thor`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if your opponent has 2 or less Life cards, that card gains an additional +2000 power during this battle.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with a cost equal to or less than the number of your opponent's Life cards.`,
  },{
    setId: SetId.OP05,
    setNumber: 115,
    cardName: `Two-Hundred Million Volts Amaru`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 2,
    effectText: `[Main] Up to 1 of your Leader or Character cards gains +3000 power during this turn. Then, if you have 1 or less Life cards, rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] You may trash 2 cards from your hand: Add up to 1 card from the top of your deck to the top of your Life cards.`,
  },{
    setId: SetId.OP05,
    setNumber: 116,
    cardName: `Hino Bird Zap`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 2,
    effectText: `[Main] K.O. up to 1 of your opponent's Characters with a cost equal to or less than the number of your opponent's Life cards.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP05,
    setNumber: 117,
    cardName: `Upper Yard`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 1,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Sky Island} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP05,
    setNumber: 118,
    cardName: `Kaido`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'SENNSU', 'akagi' ],
    blockIcon: 2,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 10,
    power: 12000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Draw 4 cards if your opponent has 3 or less Life cards.`,
  },{
    setId: SetId.OP05,
    setNumber: 119,
    cardName: `Monkey.D.Luffy`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'TAPIOCA', 'Manga', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.TheFourEmperors, TypeTags.StrawHatCrew ],
    cost: 10,
    power: 12000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] DON!! -10: Place all of your Characters except this Character at the bottom of your deck in any order. Then, take an extra turn after this one.
    [Activate: Main] [Once Per Turn] ➀: Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },
];