import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.OP06,
    setNumber: 1,
    cardName: 'Uta',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED, CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Sunohara' ],
    blockIcon: 2,
    types: [ TypeTags.FILM ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[When Attacking] You may trash 1 {FILM} type card from your hand: Give up to 1 of your opponent's Characters -2000 power during this turn. Then, add up to 1 DON!! card from your DON!! deck and rest it.`,
    life: 4,
  },{
    setId: SetId.OP06,
    setNumber: 2,
    cardName: 'Inazuma',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'COGA' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `If this Character has 7000 power or more, this Character gains [Banish].
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 3,
    cardName: 'Emporio.Ivankov',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 2,
    types: [ TypeTags.RevolutionaryArmy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Look at 3 cards from the top of your deck and play up to 1 {Revolutionary Army} type Character card with 5000 power or less. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP06,
    setNumber: 4,
    cardName: 'Baron Omatsuri',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Aidle Co.,Ltd.' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.OmatsuriIsland ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.RANGED,
    effectText: `[On Play] Play up to 1 [Lily Carnation] from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 5,
    cardName: 'Gasparde',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'tasaka' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.FormerNavy, TypeTags.GaspardePirates ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 6,
    cardName: 'Saga',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Hatori Kyoka' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.AsukaIsland ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] This Character gains +1000 power until the start of your next turn. Then, trash 1 of your {FILM} type Characters at the end of this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 7,
    cardName: 'Shanks',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'akagi', 'AKIRA EGAWA' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.TheFourEmperors, TypeTags.RedHairedPirates ],
    cost: 10,
    power: 12000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] K.O. up to 1 of your opponent's Characters with 10000 power or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 8,
    cardName: 'Schneider',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Aidle Co.,Ltd.' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.MugiwaraChase ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 9,
    cardName: 'Shuraiya',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Denim2', 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.ShipbuildingTown ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [When Attacking]/[On Block] [Once Per Turn] This Character's base power becomes the same as your opponent's Leader until the start of your next turn.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 10,
    cardName: 'Douglas Bullet',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.ThePiratesFest ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `If your Leader has the {FILM} type, this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 11,
    cardName: 'Tot Musica',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'KISUKE' ],
    blockIcon: 2,
    types: [ TypeTags.FILM ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] You may rest 1 of your [Uta] cards: This Character gains +5000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 12,
    cardName: 'Bear.King',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'SENNSU' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.TrumpPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `If your opponent has a Leader or Character with a base power of 6000 or more, this Character cannot be K.O.'d in battle.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 13,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'funbolt', 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Look at 3 cards from the top of your deck; reveal up to 1 {FILM} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Activate this card's [On Play] effect.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 14,
    cardName: 'Ratchet',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Suzume Muraichi' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.MechaIsland ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Your Opponent's Attack] You may trash any number of {FILM} type cards from your hand. Your Leader or 1 of your Characters gains +1000 power during this battle for every card trashed.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 15,
    cardName: 'Lily Carnation',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'UGUME' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.OmatsuriIsland ],
    cost: 4,
    power: 0,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] You may trash 1 of your Characters with 6000 power or more: Play up to 1 {FILM} type Character card with 2000 to 5000 power from your trash rested.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 16,
    cardName: 'Raise Max',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.RevolutionaryArmy ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may place this Character at the bottom of the owner's deck: Give up to 1 of your opponent's Characters -3000 power during this turn.`,
  },{
    setId: SetId.OP06,
    setNumber: 17,
    cardName: 'Meteor-Strike of Love',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 2,
    effectText: `[Main]/[Counter] You may add 1 card from the top of your Life cards to your hand: Up to 1 of your Leader or Character cards gains +3000 power during this turn.`,
  },{
    setId: SetId.OP06,
    setNumber: 18,
    cardName: 'Gum-Gum King Kong Gatling',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.RARE,
    artists: [ 'Anime' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 2,
    effectText: `[Main] Up to 1 of your Leader or Character cards gains +3000 power during this turn. Then, if your opponent has a Character with 7000 power or more, up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with 5000 power or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 19,
    cardName: 'Blue Dragon Seal Water Stream',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Anime' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 3,
    effectText: `[Main] K.O. up to 1 of your opponent's Characters with 5000 power or less.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with 4000 power or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 20,
    cardName: 'Hody Jones',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] You may rest this Leader: Rest up to 1 of your opponent's DON!! cards or Characters with a cost of 3 or less. Then, you cannot add Life cards to your hand using your own effects during this turn.`,
    life: 5,
  },{
    setId: SetId.OP06,
    setNumber: 21,
    cardName: 'Perona',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] Choose one:
    • Rest up to 1 of your opponent's Characters with a cost of 4 or less.
    • Give up to 1 of your opponent's Characters -1 cost during this turn.`,
    life: 4,
  },{
    setId: SetId.OP06,
    setNumber: 22,
    cardName: 'Yamato',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Sunohara' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Double Attack] (This card deals 2 damage.)
    [Activate: Main] [Once Per Turn] If your opponent has 3 or less Life cards, give up to 2 rested DON!! cards to 1 of your Characters.`,
    life: 4,
  },{
    setId: SetId.OP06,
    setNumber: 23,
    cardName: 'Arlong',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Nijihayashi' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.EastBlue, TypeTags.ArlongPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] You may trash 1 card from your hand: Up to 1 of your opponent's rested Leader cannot attack until the end of your opponent's next turn.`,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 24,
    cardName: 'Ikaros Much',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If your Leader has the {New Fish-Man Pirates} type, play up to 1 {Fish-Man} type Character card with a cost of 4 or less from your hand. Then, add 1 card from the top of your Life cards to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 25,
    cardName: 'Camie',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Koushi Rokushiro', 'Kaito Shibano' ],
    blockIcon: 2,
    types: [ TypeTags.Merfolk ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at 4 cards from the top of your deck; reveal up to 1 {Fish-Man} or {Merfolk} type card other than [Camie] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 26,
    cardName: 'Koushirou',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hayaken-sarena' ],
    blockIcon: 2,
    types: [ TypeTags.FrostMoonVillage ],
    cost: 3,
    power: 0,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Set up to 1 of your <Slash> attribute Characters with a cost of 4 or less as active. Then, you cannot attack a Leader during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 27,
    cardName: 'Gyro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.GyroPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On K.O.] Rest up to 1 of your opponent's Characters with a cost of 3 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 28,
    cardName: 'Zeo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[DON!! x1] [When Attacking] If your Leader has the {New Fish-Man Pirates} type, set up to 1 of your DON!! cards as active and this Character gains +1000 power during this turn. Then, add 1 card from the top of your Life cards to your hand.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 29,
    cardName: 'Daruma',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] [Once Per Turn] If your Leader has the {New Fish-Man Pirates} type, set this Character as active and this Character gains +1000 power during this turn. Then, add 1 card from the top of your Life cards to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 30,
    cardName: 'Dosun',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] If your Leader has the {New Fish-Man Pirates} type, this Character cannot be K.O.'d in battle and gains +2000 power until the start of your next turn. Then, add 1 card from the top of your Life cards to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 31,
    cardName: 'Hatchan',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.FormerArlongPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    triggerText: `[Trigger] Play up to 1 {Fish-Man} or {Merfolk} type Character card with a cost of 3 or less from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 32,
    cardName: 'Hammond',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'shosuke' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.RANGED,
    triggerText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 33,
    cardName: 'Vander Decken IX',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'touge369' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.FlyingPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.RANGED,
    triggerText: `[On Play] You may trash 1 {Fish-Man} type card from your hand or 1 [The Ark Noah] from your hand or field: K.O. up to 1 of your opponent's rested Characters.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 34,
    cardName: 'Hyouzou',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'touge369' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    triggerText: `[Activate: Main] [Once Per Turn] Rest up to 1 of your opponent's Characters with a cost of 4 or less and this Character gains +1000 power during this turn. Then, add 1 card from the top of your Life cards to your hand.`,
  },{
    setId: SetId.OP06,
    setNumber: 35,
    cardName: 'Hody Jones',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'HISASHI HUJIWARA', 'Hayaken-sarena' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    cost: 7,
    power: 8000,
    attribute: CardAttribute.STRIKE,
    triggerText: `[Rush] (This card can attack on the turn in which it is played.)
    [On Play] Rest up to a total of 2 of your opponent's Characters or DON!! cards. Then, add 1 card from the top of your Life cards to your hand.`,
  },{
    setId: SetId.OP06,
    setNumber: 36,
    cardName: 'Ryuma',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'eiji kaneda' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano, TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    triggerText: `[On Play]/[On K.O.] K.O. up to 1 of your opponent's rested Characters with a cost of 4 or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 37,
    cardName: 'Wadatsumi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.FlyingPirates ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 38,
    cardName: 'The Billion-fold World Trichiliocosm',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa, TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, if you have 8 or more rested cards, that card gains an additional +2000 power during this battle.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 39,
    cardName: `You Ain't Even Worth Killing Time!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 4,
    effectText: `[Main] Choose one:
    • Rest up to 1 of your opponent's Characters with a cost of 6 or less.
    • K.O. up to 1 of your opponent's rested Characters with a cost of 6 or less.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP06,
    setNumber: 40,
    cardName: `Shark Arrows`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.NewFishmanPirates ],
    cost: 2,
    effectText: `[Main] K.O. up to 2 of your opponent's rested Characters with a cost of 3 or less.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP06,
    setNumber: 41,
    cardName: `The Ark Noah`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.FishManIsland ],
    cost: 6,
    effectText: `[On Play] Rest all of your opponent's Characters.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.OP06,
    setNumber: 42,
    cardName: 'Vinsmoke Reiju',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE, CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'NIJIMAARC' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Your Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck, draw 1 card.`,
    life: 4,
  },{
    setId: SetId.OP06,
    setNumber: 43,
    cardName: 'Aramaki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'tasaka', 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    triggerText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [Activate: Main] [Once Per Turn] You may trash 1 card from your hand and place 1 Character with a cost of 2 or less at the bottom of the owner's deck: This Character gains +3000 power during this turn.`,
  },{
    setId: SetId.OP06,
    setNumber: 44,
    cardName: 'Gion',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'otton' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    triggerText: `[Your Turn] [Once Per Turn] When your opponent activates an Event, your opponent must place 1 card from their hand at the bottom of their deck.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 45,
    cardName: 'Kuzan',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'SENNSU' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    triggerText: `[On Play] Draw 2 cards and place 2 cards from your hand at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP06,
    setNumber: 46,
    cardName: 'Sakazuki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'S-KINOKO' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    triggerText: `[On Play] Place up to 1 Character with a cost of 2 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP06,
    setNumber: 47,
    cardName: 'Charlotte Pudding',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Noriko Asaka' ],
    blockIcon: 2,
    types: [ TypeTags.BigMomPirates ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.WISDOM,
    triggerText: `[On Play] Your opponent returns all cards in their hand to their deck and shuffles their deck. Then, your opponent draws 5 cards.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 48,
    cardName: 'Zeff',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.EastBlue ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    triggerText: `[Your Turn] When your opponent activates [Blocker] or an Event, if your Leader has the {East Blue} type, you may trash 4 cards from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 49,
    cardName: 'Sengoku',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'nukadokomodera' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 50,
    cardName: 'Tashigi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Aidle Co.,Ltd.', 'yuu' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Look at 5 cards from the top of your deck; reveal up to 1 {Navy} type card other than [Tashigi] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 51,
    cardName: 'Tsuru',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'otton' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] You may trash 2 cards from your hand: Your opponent returns 1 of their Characters to the owner's hand.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 52,
    cardName: 'Tokikake',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Moopic' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] If you have 4 or less cards in your hand, this Character cannot be K.O.'d in battle.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 53,
    cardName: 'Jaguar.D.Saul',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'S-KINOKO' ],
    blockIcon: 2,
    types: [ TypeTags.Giant, TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On K.O.] Place up to 1 Character with a cost of 2 or less at the bottom of the owner's deck.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 54,
    cardName: 'Borsalino',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Yoichi Amano' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `If you have 5 or less cards in your hand, this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.OP06,
    setNumber: 55,
    cardName: 'Monkey.D.Garp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'tatsuya' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x2] [When Attacking] If you have 4 or less cards in your hand, your opponent cannot activate [Blocker] during this battle.`,
  },{
    setId: SetId.OP06,
    setNumber: 56,
    cardName: 'Ama no Murakumo Sword',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 2,
    effectText: `[Main] Place up to 1 of your opponent's Characters with a cost of 2 or less and up to 1 of your opponent's Characters with a cost of 1 or less at the bottom of the owner's deck in any order.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP06,
    setNumber: 57,
    cardName: `But I Will Never Doubt a Woman's Tears!!!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa, TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Main] Up to 1 of your Leader or Character cards gains +1000 power during this turn. Then, reveal 1 card from the top of your deck, play up to 1 Character card with a cost of 2, and place the rest at the top or bottom of your deck.`,
    triggerText: `[Trigger] Play up to 1 Character card with a cost of 2 from your hand.`,
  },{
    setId: SetId.OP06,
    setNumber: 58,
    cardName: `Gravity Blade Raging Tiger`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 7,
    effectText: `[Main] Place up to 2 Characters with a cost of 6 or less at the bottom of the owner's deck in any order.`,
    triggerText: `[Trigger] Place up to 1 Character with a cost of 5 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP06,
    setNumber: 59,
    cardName: `White Snake`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.Navy ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +1000 power during this turn, and draw 1 card.`,
    triggerText: `[Trigger] Look at 5 cards from the top of your deck and place them at the top or bottom of your deck in any order.`,
  },{
    setId: SetId.OP06,
    setNumber: 60,
    cardName: 'Vinsmoke Ichiji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'UGUME' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may trash this Character: If your Leader has the {GERMA 66} type, play up to 1 [Vinsmoke Ichiji] with a cost of 7 from your hand or trash.`,
  },{
    setId: SetId.OP06,
    setNumber: 61,
    cardName: 'Vinsmoke Ichiji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Minato Sashima', 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] If the number of DON!! cards on your field is equal to or less than the number on your opponent's field, give up to 1 of your opponent's Characters -2000 power during this turn and this Character gains [Rush].
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.OP06,
    setNumber: 62,
    cardName: 'Vinsmoke Judge',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Yoichi Amano', 'ASAKI KURODA' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 8,
    power: 8000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may trash 2 cards from your hand: Play up to 4 {GERMA 66} type Character cards with different card names and 4000 power or less from your trash.
    [Activate: Main] [Once Per Turn] DON!! -1: Rest up to 1 of your opponent's DON!! cards.`,
  },{
    setId: SetId.OP06,
    setNumber: 63,
    cardName: 'Vinsmoke Sora',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Pisuke' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.KingdomOfGerma ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] You may trash 1 card from your hand: If the number of DON!! cards on your field is equal to or less than the number on your opponent's field, add up to 1 {The Vinsmoke Family} type Character card with 4000 power or less from your trash to your hand.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 64,
    cardName: 'Vinsmoke Niji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Tanaka Kenichi' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may trash this Character: If your Leader has the {GERMA 66} type, play up to 1 [Vinsmoke Niji] with a cost of 5 from your hand or trash.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 65,
    cardName: 'Vinsmoke Niji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Moopic' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] If the number of DON!! cards on your field is equal to or less than the number on your opponent's field, choose one:
    • K.O. up to 1 of your opponent's Characters with a cost of 2 or less.
    • Return up to 1 of your opponent's Characters with a cost of 4 or less to the owner's hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 66,
    cardName: 'Vinsmoke Yonji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'phima' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may trash this Character: If your Leader has the {GERMA 66} type, play up to 1 [Vinsmoke Yonji] with a cost of 4 from your hand or trash.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 67,
    cardName: 'Vinsmoke Yonji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Sunohara' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `If the number of DON!! cards on your field is equal to or less than the number on your opponent's field, this Character gains +1000 power.
    [Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 68,
    cardName: 'Vinsmoke Reiju',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Bashikou' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.) You may trash this Character: If your Leader has the {GERMA 66} type, play up to 1 [Vinsmoke Reiju] with a cost of 4 from your hand or trash.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 69,
    cardName: 'Vinsmoke Reiju',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'SHIE NANAHARA', 'Hashimoto Q' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] If the number of DON!! cards on your field is equal to or less than the number on your opponent's field and you have 5 or less cards in your hand, draw 2 cards.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 70,
    cardName: 'Eldoraggo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'tasaka' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.EldoraggoCrew ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 71,
    cardName: 'Gild Tesoro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'tatsuya' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.Grantesoro ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): If your Leader has the {FILM} type, add up to 2 {FILM} type Character cards with a cost of 4 or less from your trash to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 72,
    cardName: 'Cosette',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Sunohara' ],
    blockIcon: 2,
    types: [ TypeTags.KingdomOfGerma ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `If your Leader has the {GERMA 66} type and the number of DON!! cards on your field is at least 2 less than the number on your opponent's field, this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 73,
    cardName: 'Shiki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.GoldenLionPirates ],
    cost: 2,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] If you have 8 or more DON!! cards on your field, draw 1 card and trash 1 card from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 74,
    cardName: 'Zephyr (Navy)',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'S-KINOKO' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.Navy ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Negate the effect of up to 1 of your opponent's Characters during this turn. Then, if that Character has 5000 power or less, K.O. it.`,
  },{
    setId: SetId.OP06,
    setNumber: 75,
    cardName: 'Count Battler',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Minato Sashima' ],
    blockIcon: 2,
    types: [ TypeTags.FILM, TypeTags.CrownIsland ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Rest up to 2 of your opponent's Characters with a cost of 2 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 76,
    cardName: 'Hitokiri Kamazo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Denim2' ],
    blockIcon: 2,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates, TypeTags.SMILE ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[Your Turn] [Once Per Turn] When a DON!! card on your field is returned to your DON!! deck, K.O. up to 1 of your opponent's Characters with a cost of 2 or less.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 77,
    cardName: 'Black Bug',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 4,
    effectText: `[Main] If the number of DON!! cards on your field is equal to or less than the number on your opponent's field, place up to 1 of your opponent's Characters with a cost of 5 or less at the bottom of the owner's deck.`,
    triggerText: `[Trigger] Place up to 1 of your opponent's Characters with a cost of 4 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.OP06,
    setNumber: 78,
    cardName: 'GERMA 66',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.TheVinsmokeFamily, TypeTags.GERMA66 ],
    cost: 1,
    effectText: `[Main] Look at 5 cards from the top of your deck; reveal up to 1 card with a type including "GERMA" other than [GERMA 66] and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
    triggerText: `[Trigger] Draw 1 card.`,
  },{
    setId: SetId.OP06,
    setNumber: 79,
    cardName: 'Kingdom of GERMA',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.KingdomOfGerma ],
    cost: 1,
    effectText: `[Activate: Main] You may trash 1 card from your hand and rest this Stage: Look at 3 cards from the top of your deck; reveal up to 1 card with a type including "GERMA" and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP06,
    setNumber: 80,
    cardName: 'Gecko Moria',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.ThrillerBarkPirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] [When Attacking] ➁ (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: Trash 2 cards from the top of your deck and play up to 1 {Thriller Bark Pirates} type Character card with a cost of 4 or less from your trash.`,
    life: 5,
  },{
    setId: SetId.OP06,
    setNumber: 81,
    cardName: 'Absalom',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hayaken-sarena', 'BISAI' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.RANGED,
    effectText: `[On Play] You may return 2 cards from your trash to the bottom of your deck in any order: K.O. up to 1 Character with a cost of 2 or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 82,
    cardName: 'Inuppe',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play]/[On K.O.] If your Leader has the {Thriller Bark Pirates} type, draw 2 cards and trash 2 cards from your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 83,
    cardName: 'Oars',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'DAI-XT.' ],
    blockIcon: 2,
    types: [ TypeTags.Giant, TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `This Character cannot attack.
    [Activate: Main] You may K.O. 1 of your {Thriller Bark Pirates} type Characters: This Character's effect is negated during this turn.`,
  },{
    setId: SetId.OP06,
    setNumber: 84,
    cardName: 'Jigoro of the Wind',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[On K.O.] Up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 85,
    cardName: 'Kumacy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'kito' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x2] [Your Turn] This Character gains +1000 power for every 5 cards in your trash.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 86,
    cardName: 'Gecko Moria',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'eiji kaneda', 'Yosuke Adachi' ],
    blockIcon: 2,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.ThrillerBarkPirates ],
    cost: 8,
    power: 9000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Choose up to 1 Character card with a cost of 4 or less and up to 1 Character card with a cost of 2 or less from your trash. Play 1 card and play the other card rested.`,
  },{
    setId: SetId.OP06,
    setNumber: 87,
    cardName: 'Cerberus',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nakamaru' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 88,
    cardName: 'Sai',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Yasushi Yamaguchi' ],
    blockIcon: 2,
    types: [ TypeTags.Dressrosa, TypeTags.HapposuiArmy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `If your Leader has the {Dressrosa} type and is active, this Character gains +2000 power.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 89,
    cardName: 'Taralan',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play]/[On K.O.] Trash 3 cards from the top of your deck.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 90,
    cardName: 'Dr. Hogback',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] You may return 2 cards from your trash to the bottom of your deck in any order: Add up to 1 {Thriller Bark Pirates} type card other than [Dr. Hogback] from your trash to your hand.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 91,
    cardName: 'Victoria Cindry',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'BISAI' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If your Leader has the {Thriller Bark Pirates} type, trash 5 cards from the top of your deck.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 92,
    cardName: 'Brook',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Nakamaru' ],
    blockIcon: 2,
    types: [ TypeTags.FormerRumbarPirates ],
    cost: 6,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] Choose one:
    • Trash up to 1 of your opponent's Characters with a cost of 4 or less.
    • Your opponent places 3 cards from their trash at the bottom of their deck in any order.`,
  },{
    setId: SetId.OP06,
    setNumber: 93,
    cardName: 'Perona',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hokuyuu', 'Koushi Rokushiro' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] If your opponent has 5 or more cards in their hand, choose one:
    • Your opponent trashes 1 card from their hand.
    • Give up to 1 of your opponent's Characters -3 cost during this turn.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 94,
    cardName: 'Lola',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 95,
    cardName: 'Shadows Asgard',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.ThrillerBarkPirates ],
    cost: 2,
    effectText: `[Main]/[Counter] Your Leader gains +1000 power during this turn. Then, you may K.O. any number of your {Thriller Bark Pirates} type Characters with a cost of 2 or less. Your Leader gains an additional +1000 power during this turn for every Character K.O.'d.`,
    triggerText: `[Trigger] Draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.OP06,
    setNumber: 96,
    cardName: '...Nothing...at All!!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 3,
    effectText: `[Counter] You may add 1 card from the top of your Life cards to your hand: Your Characters with a cost of 7 or less cannot be K.O.'d in battle during this turn.`,
    triggerText: `[Trigger] Activate this card's [Counter] effect.`,
  },{
    setId: SetId.OP06,
    setNumber: 97,
    cardName: 'Negative Hollow',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 2,
    effectText: `[Main] Trash 1 card from your opponent's hand.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.OP06,
    setNumber: 98,
    cardName: 'Thriller Bark',
    cardType: CardType.STAGE,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.ThrillerBarkPirates ],
    cost: 1,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this Stage: If your Leader has the {Thriller Bark Pirates} type, play up to 1 {Thriller Bark Pirates} type Character card with a cost of 2 or less from your trash rested.`,
  },{
    setId: SetId.OP06,
    setNumber: 99,
    cardName: 'Aisa',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Nekobayashi' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 1,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at up to 1 card from the top of your or your opponent's Life cards and place it at the top or bottom of the Life cards.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 100,
    cardName: 'Inuarashi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Yasushi Yamaguchi' ],
    blockIcon: 2,
    types: [ TypeTags.Minks, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x2] [When Attacking] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost equal to or less than the number of your opponent's Life cards.`,
    triggerText: `[Trigger] If your opponent has 3 or less Life cards, play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 101,
    cardName: 'O-Nami',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Hagane Tsurugi', 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Up to 1 of your Leader or Character cards gains [Banish] during this turn.
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 5 or less.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 102,
    cardName: 'Kamakiri',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.ShandianWarrior ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] [Once Per Turn] You may place 1 Stage with a cost of 1 at the bottom of the owner's deck: K.O. up to 1 of your opponent's Characters with a cost of 2 or less.`,
    triggerText: `[Trigger] If you have 2 or less Life cards, play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 103,
    cardName: 'Kawamatsu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Yasushi Yamaguchi' ],
    blockIcon: 2,
    types: [ TypeTags.FishMan, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] You may trash 2 cards from your hand: Add up to 1 of your Characters with 0 power to the top or bottom of the owner's Life cards face-up.`,
    triggerText: `[Trigger] If your opponent has 3 or less Life cards, play this card.`,
  },{
    setId: SetId.OP06,
    setNumber: 104,
    cardName: 'Kikunojo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'BISAI' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[On K.O.] If your opponent has 3 or less Life cards, add up to 1 card from the top of your deck to the top of your Life cards.`,
    triggerText: `[Trigger] If your opponent has 3 or less Life cards, play this card.`,
  },{
    setId: SetId.OP06,
    setNumber: 105,
    cardName: 'Genbo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'touge369' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.ShandianWarrior ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 106,
    cardName: 'Kouzuki Hiyori',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Mayu Sakai', 'Koushi Rokushiro' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] You may add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 card from your hand to the top of your Life cards.`,
    counter: 2000,
  },{
    setId: SetId.OP06,
    setNumber: 107,
    cardName: 'Kouzuki Momonosuke',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Nijihayashi', 'Hokuyuu' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] Add up to 1 of your {Land of Wano} type Characters other than [Kouzuki Momonosuke] to the top or bottom of the owner's Life cards face-up.`,
  },{
    setId: SetId.OP06,
    setNumber: 108,
    cardName: 'Tenguyama Hitetsu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Yasushi Yamaguchi' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    triggerText: `[Trigger] Up to 1 of your {Land of Wano} type Leader or Character cards gains +2000 power during this turn.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 109,
    cardName: 'Denjiro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'eiji kaneda' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x2] If your opponent has 3 or less Life cards, this Character cannot be K.O.'d by effects.`,
    triggerText: `[Trigger] If your opponent has 3 or less Life cards, play this card.`,
  },{
    setId: SetId.OP06,
    setNumber: 110,
    cardName: 'Nekomamushi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 2,
    types: [ TypeTags.Minks, TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x2] This Character can also attack your opponent's active Characters.`,
    triggerText: `[Trigger] If your opponent has 3 or less Life cards, play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 111,
    cardName: 'Braham',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.ShandianWarrior ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.RANGED,
    effectText: `[Activate: Main] [Once Per Turn] You may place 1 Stage with a cost of 1 at the bottom of the owner's deck: Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] If you have 2 or less Life cards, play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 112,
    cardName: 'Raizo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 2,
    types: [ TypeTags.LandOfWano, TypeTags.TheAkazayaNine ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] You may trash 1 card from your hand: Rest up to 1 of your opponent's DON!! cards.`,
    triggerText: `[Trigger] If your opponent has 3 or less Life cards, play this card.`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 113,
    cardName: 'Raki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'eiji kaneda' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.ShandianWarrior ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.RANGED,
    effectText: `If you have a {Shandian Warrior} type Character other than [Raki], this Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    counter: 1000,
  },{
    setId: SetId.OP06,
    setNumber: 114,
    cardName: 'Wyper',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.UNCOMMON,
    artists: [ 'Morechand' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.ShandianWarrior ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.RANGED,
    effectText: `[On Play] You may place 1 Stage with a cost of 1 at the bottom of the owner's deck: Look at 5 cards from the top of your deck; reveal up to 1 [Upper Yard] or {Shandian Warrior} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.OP06,
    setNumber: 115,
    cardName: `You're the One Who Should Disappear.`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 0,
    effectText: `[Counter] You may trash 1 card from your hand: Up to 1 of your Leader or Character cards gains +3000 power during this battle.`,
    triggerText: `[Trigger] If you have 0 Life cards, you may add up to 1 card from the top of your deck to the top of your Life cards. Then, trash 1 card from your hand.`,
  },{
    setId: SetId.OP06,
    setNumber: 116,
    cardName: `Reject`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.RARE,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland, TypeTags.ShandianWarrior ],
    cost: 4,
    effectText: `[Main] Choose one:
    • K.O. up to 1 of your opponent's Characters with a cost of 5 or less.
    • If your opponent has 1 Life card, deal 1 damage to your opponent. Then, add 1 card from the top of your Life cards to your hand.`,
    triggerText: `[Trigger] Draw 1 card.`,
  },{
    setId: SetId.OP06,
    setNumber: 117,
    cardName: `The Ark Maxim`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.SkyIsland ],
    cost: 1,
    effectText: `[Activate: Main] [Once Per Turn] You may rest this card and 1 of your [Enel] cards: K.O. all of your opponent's Characters with a cost of 2 or less.`,
  },{
    setId: SetId.OP06,
    setNumber: 118,
    cardName: `Roronoa Zoro`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'NIJIMAARC', 'Anime', 'Manga' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 9,
    power: 9000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] [Once Per Turn] ➀ (You may rest the specified number of DON!! cards in your cost area.): Set this Character as active.
    [Activate: Main] [Once Per Turn] ➁ (You may rest the specified number of DON!! cards in your cost area.): Set this Character as active.`,
  },{
    setId: SetId.OP06,
    setNumber: 119,
    cardName: `Sanji`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SECRET_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'NIJIMAARC', 'BISAI' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 9,
    power: 9000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Reveal 1 card from the top of your deck and play up to 1 Character with a cost of 9 or less other than [Sanji]. Then, place the rest at the bottom of your deck.`,
  },
];