import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.P,
    setNumber: 1,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artVariants: [ ArtVariant.PARALLEL, ArtVariant.SPECIAL_PARALLEL ],
    artists: [ 'Manga', 'Anime', 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x2] This Character gains [Rush].
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.P,
    setNumber: 2,
    cardName: 'I Smell Adventure!!!',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Main] Return all cards in your hand to your deck and shuffle your deck. Then, draw cards equal to the number you returned to your deck.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.P,
    setNumber: 3,
    cardName: 'Eustass"Captain"Kid',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[DON!! x2] This Character gains [Double Attack].
    (This card deals 2 damage.)`,
  },{
    setId: SetId.P,
    setNumber: 4,
    cardName: 'Crocodile',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[DON!! x1] This Character gains [Blocker].
    (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.P,
    setNumber: 5,
    cardName: 'Kaido',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 7,
    power: 8000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] DON!! -2 (You may return the specified number of DON!! cards from your field to your DON!! deck.): This Character gains [Banish] during this turn.
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
  },{
    setId: SetId.P,
    setNumber: 6,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x2] [Your Turn] This Character gains +2000 power.`,
  },{
    setId: SetId.P,
    setNumber: 7,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Misa Tsutsui' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[DON!! x1] This Character cannot be K.O.'d in battle by <Strike> attribute Leaders or Characters.`,
  },{
    setId: SetId.P,
    setNumber: 8,
    cardName: 'Yamato',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Yosuke Adachi' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] You may rest this Character: Rest 1 of your opponent's Characters with a cost of 2 or less.`,
  },{
    setId: SetId.P,
    setNumber: 9,
    cardName: 'Trafalgar Law',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Nekobayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HeartPirates ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If your opponent has 6 or more cards in their hand, your opponent adds 1 card from their Life area to their hand.`,
  },{
    setId: SetId.P,
    setNumber: 10,
    cardName: 'Kaido',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 8,
    power: 9000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[End of Your Turn] Add 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.P,
    setNumber: 11,
    cardName: 'Uta',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.LEADER,
    artists: [ 'Eiichiro Oda' ],
    blockIcon: 1,
    types: [ TypeTags.FILM ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] ① (You may rest the specified number of DON!! cards in your cost area.): Up to 1 of your Characters with no base effect gains +2000 power during this turn.`,
    life: 5,
  },{
    setId: SetId.P,
    setNumber: 12,
    cardName: 'Jellyfish Pirates',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.JellyfishPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 13,
    cardName: 'Gordon',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] You may place this Character at the bottom of the owner's deck: Give up to 1 of your opponent's Characters -3000 power during this turn.`,
  },{
    setId: SetId.P,
    setNumber: 14,
    cardName: 'Koby',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Navy ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.P,
    setNumber: 15,
    cardName: 'Sunny-Kun',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Banpresto' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.StrawHatCrew ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 16,
    cardName: 'Shanks',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Eiichiro Oda' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.TheFourEmperors, TypeTags.RedHairedPirates ],
    cost: 8,
    power: 10000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 17,
    cardName: 'Trafalgar Law',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Banpresto' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.HeartPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Give up to 1 of your opponent's Characters -2000 power during this turn.`,
  },{
    setId: SetId.P,
    setNumber: 18,
    cardName: 'Bartolomeo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Banpresto' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.BartoClub ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.P,
    setNumber: 19,
    cardName: 'Bepo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Minks, TypeTags.HeartPirates ],
    cost: 3,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] K.O. up to 1 of your opponent's Characters with 3000 power or less.`,
  },{
    setId: SetId.P,
    setNumber: 20,
    cardName: 'Helmeppo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Navy ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
  },{
    setId: SetId.P,
    setNumber: 21,
    cardName: 'Benn.Beckman',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'DAI-XT.' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.RedHairedPirates ],
    cost: 7,
    power: 9000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 22,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Eiichiro Oda' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 23,
    cardName: 'Yasopp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'DAI-XT.' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.RedHairedPirates ],
    cost: 6,
    power: 8000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 24,
    cardName: `I'm Gonna Be King of the Pirates!!`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.StrawHatCrew ],
    cost: 2,
    effectText: `[Main] Your Leader gains +1000 power for each of your Characters during this turn.`,
    triggerText: `[Trigger] Up to 1 of your Leader or Character cards gains +1000 power during this turn.`,
  },{
    setId: SetId.P,
    setNumber: 26,
    cardName: `Morgan`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Koushi Rokushiro' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[When Attacking] Give up to 1 of your opponent's Characters -3 cost during this turn.`,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 27,
    cardName: `General Franky`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Naochika Morishita' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.RANGED,
    effectText: `Also treat this card's name as [Franky] according to the rules.
    [Opponent's Turn] All of your Characters with 3000 base power or less gain +1000 power.`,
  },{
    setId: SetId.P,
    setNumber: 28,
    cardName: 'Portgas.D.Ace',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.RED ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Sunohara' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.WhitebeardPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Double Attack] (This card deals 2 damage.)`,
  },{
    setId: SetId.P,
    setNumber: 29,
    cardName: 'Bartolomeo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'TAPIOCA' ],
    blockIcon: 1,
    types: [ TypeTags.FILM, TypeTags.Supernovas, TypeTags.BartoClub ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[End of Your Turn] You may rest this Character: Set up to 1 of your {FILM} type Characters other than [Bartolomeo] as active.`,
  },{
    setId: SetId.P,
    setNumber: 30,
    cardName: 'Jinbe',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'SOWSOW' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.TheSevenWarlordsOfTheSea, TypeTags.TheSunPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[On K.O.] Place up to 1 Character with a cost of 3 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.P,
    setNumber: 31,
    cardName: 'Uta',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Sunohara' ],
    blockIcon: 1,
    types: [ TypeTags.FILM ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Add up to 1 DON!! card from your DON!! deck and rest it.`,
  },{
    setId: SetId.P,
    setNumber: 32,
    cardName: 'Sengoku',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'tasaka' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.WISDOM,
    effectText: `[DON!! x1] [Your Turn] Give all of your opponent's Characters -2 cost.`,
  },{
    setId: SetId.P,
    setNumber: 33,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] You may place this Character at the bottom of the owner's deck: Draw 1 card.`,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 34,
    cardName: 'Sanji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Hatori Kyoka' ],
    blockIcon: 1,
    types: [ TypeTags.TheVinsmokeFamily ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [Your Turn] If you have 2 or less Life cards, this Character gains +2000 power.`,
    counter: 1000,
  },{
    setId: SetId.P,
    setNumber: 37,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.PROMOTIONAL,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.StrawHatCrew ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] If you have 2 or more rested Characters, this Character gains +1000 power during this turn.`,
  },
];