import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.ST02,
    setNumber: 1,
    cardName: 'Eustass"Captain"Kid',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.LEADER,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] ③ (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: Set this Leader as active.`,
    life: 5,
  },{
    setId: SetId.ST02,
    setNumber: 2,
    cardName: 'Vito',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.FiretankPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.ST02,
    setNumber: 3,
    cardName: 'Urouge',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.FallenMonkPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[DON!! x1] If you have 3 or more Characters, this card gains +2000 power.`,
  },{
    setId: SetId.ST02,
    setNumber: 4,
    cardName: 'Capone"Gang"Bege',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.FiretankPirates ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.ST02,
    setNumber: 5,
    cardName: 'Killer',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] K.O. up to 1 of your opponent's rested Characters with a cost of 3 or less.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.ST02,
    setNumber: 6,
    cardName: 'Koby',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST02,
    setNumber: 7,
    cardName: 'Jewelry Bonney',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.BonneyPirates ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Activate: Main] ➀ (You may rest the specified number of DON!! cards in your cost area.) You may rest this card: Look at 5 cards from the top of your deck; reveal up to 1 {Supernovas} type card and add it to your hand. Then, place the rest at the bottom of your deck in any order.`,
  },{
    setId: SetId.ST02,
    setNumber: 8,
    cardName: 'Scratchmen Apoo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.OnAirPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.RANGED,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] Rest up to 1 of your opponent's DON!! cards.`,
  },{
    setId: SetId.ST02,
    setNumber: 9,
    cardName: 'Trafalgar Law',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HeartPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Set up to 1 of your {Supernovas} or {Heart Pirates} type rested Characters with a cost of 5 or less as active.`,
  },{
    setId: SetId.ST02,
    setNumber: 10,
    cardName: 'Basil Hawkins',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HawkinsPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [Once Per Turn] [Your Turn] If this Character battles your opponent's Character, set this card as active.`,
  },{
    setId: SetId.ST02,
    setNumber: 11,
    cardName: 'Heat',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.KidPirates ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.ST02,
    setNumber: 12,
    cardName: 'Bepo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Minks, TypeTags.HeartPirates ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST02,
    setNumber: 13,
    cardName: 'Eustass"Captain"Kid',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [DON!! x1] [End of Your Turn] Set this card as active.`,
  },{
    setId: SetId.ST02,
    setNumber: 14,
    cardName: 'X.Drake',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Navy, TypeTags.Supernovas, TypeTags.DrakePirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [Your Turn] If this Character is rested, your {Supernovas} or {Navy} type Leaders and Characters gain +1000 power.`,
  },{
    setId: SetId.ST02,
    setNumber: 15,
    cardName: 'Scalpel',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HeartPirates ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, set up to 1 of your DON!! cards as active.`,
    triggerText: `[Trigger] Set up to 2 of your DON!! cards as active.`,
  },{
    setId: SetId.ST02,
    setNumber: 16,
    cardName: 'Repel',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.KidPirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, set up to 1 of your DON!! cards as active.`,
  },{
    setId: SetId.ST02,
    setNumber: 17,
    cardName: 'Straw Sword',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Supernovas, TypeTags.HawkinsPirates ],
    cost: 2,
    effectText: `[Main] Rest up to 1 of your opponent's Characters.`,
    triggerText: `[Trigger] Play up to 1 {Supernovas} type card with a cost of 2 or less from your hand.`,
  },
];