import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.ST03,
    setNumber: 1,
    cardName: 'Crocodile',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] DON!! -4 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Return up to 1 Character with a cost of 5 or less to the owner's hand.`,
    life: 5,
  },{
    setId: SetId.ST03,
    setNumber: 2,
    cardName: 'Edward Weevil',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST03,
    setNumber: 3,
    cardName: 'Crocodile',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [DON!! x1] [On Block] Place up to 1 Character with a cost of 2 or less at the bottom of the owner's deck.`,
  },{
    setId: SetId.ST03,
    setNumber: 4,
    cardName: 'Gecko Moria',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On Play] Add up to 1 {The Seven Warlords of the Sea} or {Thriller Bark Pirates} type Character with a cost of 4 or less other than [Gecko Moria] from your trash to your hand.`,
  },{
    setId: SetId.ST03,
    setNumber: 5,
    cardName: 'Dracule Mihawk',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 2000,
    effectText: `[DON!! x1] [When Attacking] Draw 2 cards and trash 2 cards from your hand.`,
  },{
    setId: SetId.ST03,
    setNumber: 6,
    cardName: 'Jinbe',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.FishMan, TypeTags.TheSevenWarlordsOfTheSea, TypeTags.TheSunPirates ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST03,
    setNumber: 7,
    cardName: 'Sentomaru',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[DON!! x1] [Activate: Main] [Once Per Turn] ➁ (You may rest the specified number of DON!! cards in your cost area.): Play up to 1 [Pacifista] with a cost of 4 or less from your deck, then shuffle your deck.`,
  },{
    setId: SetId.ST03,
    setNumber: 8,
    cardName: 'Trafalgar Law',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.HeartPirates ],
    cost: 1,
    power: 1000,
    attribute: CardAttribute.SLASH,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.ST03,
    setNumber: 9,
    cardName: 'Donquixote Doflamingo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.DonquixotePirates ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Return up to 1 Character with a cost of 7 or less to the owner's hand.`,
  },{
    setId: SetId.ST03,
    setNumber: 10,
    cardName: 'Bartholomew Kuma',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.RevolutionaryArmy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Look at 3 cards from the top of your deck and return them to the top or bottom of the deck in any order.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.ST03,
    setNumber: 11,
    cardName: 'Buggy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BuggysDelivery ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST03,
    setNumber: 12,
    cardName: 'Pacifista',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.BiologicalWeapon, TypeTags.Navy ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.ST03,
    setNumber: 13,
    cardName: 'Boa Hancock',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.KujaPirates ],
    cost: 3,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.ST03,
    setNumber: 14,
    cardName: 'Marshall.D.Teach',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BlackbeardPirates ],
    cost: 4,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[On Play] Return up to 1 Character with a cost of 3 or less to the owner's hand.`,
  },{
    setId: SetId.ST03,
    setNumber: 15,
    cardName: 'Sables',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.BaroqueWorks ],
    cost: 4,
    effectText: `[Main] Return up to 1 Character with a cost of 7 or less to the owner's hand.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.ST03,
    setNumber: 16,
    cardName: 'Thrust Pad Cannon',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.RevolutionaryArmy ],
    cost: 2,
    effectText: `[Counter] Return up to 1 Character with a cost of 3 or less to the owner's hand.`,
    triggerText: `[Trigger] Activate this card's [Counter] effect.`,
  },{
    setId: SetId.ST03,
    setNumber: 17,
    cardName: 'Love-Love Mellow',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.KujaPirates ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, draw 1 card if you have 3 or less cards in your hand.`,
  },
];