import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.ST04,
    setNumber: 1,
    cardName: 'Kaido',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.LEADER,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] [Once Per Turn] DON!! -7 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Trash up to 1 of your opponent's Life cards.`,
    life: 5,
  },{
    setId: SetId.ST04,
    setNumber: 2,
    cardName: 'Ulti',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 2000,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Play up to 1 [Page One] card with a cost of 4 or less from your hand.`,
  },{
    setId: SetId.ST04,
    setNumber: 3,
    cardName: 'Kaido',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Manga', 'WANTED' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 9,
    power: 10000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] DON!! -5 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 6 or less. This Character gains [Rush] during this turn.
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.ST04,
    setNumber: 4,
    cardName: 'King',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.ST04,
    setNumber: 5,
    cardName: 'Queen',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Draw 2 cards and trash 1 card from your hand.`,
  },{
    setId: SetId.ST04,
    setNumber: 6,
    cardName: 'Sasaki',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Draw 1 card.`,
  },{
    setId: SetId.ST04,
    setNumber: 7,
    cardName: 'Sheepshead',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.Smile ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST04,
    setNumber: 8,
    cardName: 'Jack',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artVariants: [ ArtVariant.PARALLEL ],
    artists: [ 'Anime', 'Hayaken-sarena' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[On Play] You may trash 1 card from your hand: Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.ST04,
    setNumber: 9,
    cardName: 'Ginrummy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates, TypeTags.Smile ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST04,
    setNumber: 10,
    cardName: `Who's.Who`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): K.O. up to 1 of your opponent's Characters with a cost of 3 or less.`,
    triggerText: `[Trigger] Play this card.`,
  },{
    setId: SetId.ST04,
    setNumber: 11,
    cardName: `Black Maria`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.ST04,
    setNumber: 12,
    cardName: `Page One`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST04,
    setNumber: 13,
    cardName: `X.Drake`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.Navy, TypeTags.DrakePirates, TypeTags.AnimalKingdomPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST04,
    setNumber: 14,
    cardName: `Lead Performer "Disaster"`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    effectText: `[Main] Draw 1 card, then add up to 1 DON!! card from your DON!! deck and set it as active.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.ST04,
    setNumber: 15,
    cardName: `Brachio Bomber`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 6,
    effectText: `[Main] K.O. up to 1 of your opponent's Characters with a cost of 6 or less, then add up to 1 DON!! card from your DON!! deck and set it as active.`,
    triggerText: `[Trigger] Add up to 1 DON!! card from your DON!! deck and set it as active.`,
  },{
    setId: SetId.ST04,
    setNumber: 16,
    cardName: `Blast Breath`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.AnimalKingdomPirates ],
    cost: 1,
    effectText: `[Counter] DON!! -1 (You may return the specified number of DON!! cards from your field to your DON!! deck.): Up to 1 of your Leader or Character cards gains +4000 power during this battle.`,
  },{
    setId: SetId.ST04,
    setNumber: 17,
    cardName: `Onigashima Island`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.PURPLE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Kazuyuki Hayashi' ],
    imgObjs: [ '_D.png' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 3,
    effectText: `[Activate: Main] You may rest this Stage: If your Leader has the {Animal Kingdom Pirates} type, add up to 1 DON!! card from your DON!! deck and rest it.`,
  },
];