import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.ST06,
    setNumber: 1,
    cardName: 'Sakazuki',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.LEADER,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] [Once Per Turn] ③ (You may rest the specified number of DON!! cards in your cost area.) You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 0.`,
    life: 5,
  },{
    setId: SetId.ST06,
    setNumber: 2,
    cardName: 'Koby',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    power: 2000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
    effectText: `[On Play] You may trash 1 card from your hand: K.O. up to 1 of your opponent's Characters with a cost of 0.`,
  },{
    setId: SetId.ST06,
    setNumber: 3,
    cardName: 'Jango',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST06,
    setNumber: 4,
    cardName: 'Smoker',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Nijihayashi' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `This Character cannot be K.O.'d by effects.
    [DON!! x1] If there is a Character with a cost of 0, this Character gains [Double Attack].
    (This card deals 2 damage.)`,
  },{
    setId: SetId.ST06,
    setNumber: 5,
    cardName: 'Sengoku',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `[When Attacking] Give up to 1 of your opponent's Characters -4 cost during this turn.`,
  },{
    setId: SetId.ST06,
    setNumber: 6,
    cardName: 'Tashigi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 2000,
    effectText: `[Activate: Main] You may rest this Character: Give up to 1 of your opponent's Characters -2 cost during this turn.`,
  },{
    setId: SetId.ST06,
    setNumber: 7,
    cardName: 'Tsuru',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
  },{
    setId: SetId.ST06,
    setNumber: 8,
    cardName: 'Hina',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Give up to 1 of your opponent's Characters -4 cost during this turn.`,
  },{
    setId: SetId.ST06,
    setNumber: 9,
    cardName: 'Fullbody',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST06,
    setNumber: 10,
    cardName: 'Helmeppo',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
    effectText: `[On Play] Give up to 1 of your opponent's Characters -3 cost during this turn.`,
  },{
    setId: SetId.ST06,
    setNumber: 11,
    cardName: 'Momonga',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST06,
    setNumber: 12,
    cardName: 'Monkey.D.Garp',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Activate: Main] You may trash 1 card from your hand and rest this Character: K.O. up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.ST06,
    setNumber: 13,
    cardName: 'T-Bone',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST06,
    setNumber: 14,
    cardName: `Shockwave`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, K.O. up to 1 of your opponent's active Characters with a cost of 3 or less.`,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 4 or less.`,
  },{
    setId: SetId.ST06,
    setNumber: 15,
    cardName: `Great Eruption`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    effectText: `[Main] Draw 1 card. Then, give up to 1 of your opponent's Characters -2 cost during this turn.`,
    triggerText: `[Trigger] Your opponent chooses 1 card from their hand and trashes it.`,
  },{
    setId: SetId.ST06,
    setNumber: 16,
    cardName: `White Out`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle.`,
    triggerText: `[Trigger] Draw 1 card and none of your Characters can be K.O.'d during this turn.`,
  },{
    setId: SetId.ST06,
    setNumber: 17,
    cardName: `Navy HQ`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.BLACK ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Navy ],
    cost: 1,
    effectText: `[On Play] Give up to 1 of your opponent's Characters -1 cost during this turn.
    [Activate: Main] You may rest this Stage: If your Leader has the {Navy} type, give up to 1 of your opponent's Characters -1 cost during this turn.`,
  },
];