import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  ArtVariant,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.ST07,
    setNumber: 1,
    cardName: 'Charlotte Linlin',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x2] [When Attacking] You may add 1 card from the top or bottom of your Life cards to your hand: If you have 2 or less Life cards, add up to 1 card from your hand to the top of your Life cards.`,
    life: 5,
  },{
    setId: SetId.ST07,
    setNumber: 2,
    cardName: 'Charlotte Anana',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 3,
    cardName: 'Charlotte Katakuri',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Look at up to 1 card from the top of your or your opponent's Life cards, and place it at the top or bottom of the Life cards. Then, if you have less Life cards than your opponent, this Character gains [Rush] during this turn.
    (This card can attack on the turn in which it is played.)`,
  },{
    setId: SetId.ST07,
    setNumber: 4,
    cardName: 'Charlotte Snack',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] You may add 1 card from the top or bottom of your Life cards to your hand: This Character gains [Banish] and +1000 power during this battle.
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
  },{
    setId: SetId.ST07,
    setNumber: 5,
    cardName: 'Charlotte Daifuku',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'kankurou' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] You may add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 card from the top of your deck to the top of your Life cards.`,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 6,
    cardName: 'Charlotte Flampe',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.RANGED,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 7,
    cardName: 'Charlotte Brulee',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    power: 1000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 8,
    cardName: 'Charlotte Pudding',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] Look at up to 1 card from the top of your or your opponent's Life cards, and place it at the top or bottom of the Life cards.`,
    counter: 2000,
  },{
    setId: SetId.ST07,
    setNumber: 9,
    cardName: `Charlotte Mont-d'or`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] You may rest this Character and add 1 card from the top or bottom of your Life cards to your hand: K.O. up to 1 of your opponent's Characters with a cost of 3 or less.`,
    triggerText: `[Trigger] You may trash 1 card from your hand: Play this card.`,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 10,
    cardName: `Charlotte Linlin`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'BISAI' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    cost: 7,
    power: 8000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Your opponent chooses one:
    • Trash 1 card from the top of your opponent's Life cards.
    • Add 1 card from the top of your deck to the top of your Life cards.`,
  },{
    setId: SetId.ST07,
    setNumber: 11,
    cardName: `Zeus`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] You may rest this Character: Up to 1 of your [Charlotte Linlin] cards gains [Banish] during this turn.
    (When this card deals damage, the target card is trashed without activating its Trigger.)`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 12,
    cardName: `Baron Tamago`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 13,
    cardName: `Prometheus`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'HISASHI HUJIWARA' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Activate: Main] You may rest this Character: Up to 1 of your [Charlotte Linlin] cards gains [Double Attack] during this turn.
    (This card deals 2 damage.)`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 14,
    cardName: `Pekoms`,
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anime' ],
    blockIcon: 1,
    types: [ TypeTags.Minks, TypeTags.BigMomPirates ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST07,
    setNumber: 15,
    cardName: `Soul Pocus`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.TheFourEmperors, TypeTags.BigMomPirates ],
    cost: 5,
    effectText: `[Main] Your opponent chooses one:
    • Trash 1 card from the top of your opponent's Life cards.
    • Add 1 card from the top of your deck to the top of your Life cards.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.ST07,
    setNumber: 16,
    cardName: `Power Mochi`,
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates ],
    cost: 1,
    effectText: `[Counter] Look at up to 1 card from the top of your or your opponent's Life cards, and place it at the top or bottom of the Life cards. Then, up to 1 of your Leader or Character cards gains +2000 power during this battle.`,
    triggerText: `[Trigger] Draw 1 card, look at up to 1 card from the top of your or your opponent's Life cards, and place it at the top or bottom of the Life cards.`,
  },{
    setId: SetId.ST07,
    setNumber: 17,
    cardName: `Queen Mama Chanter`,
    cardType: CardType.STAGE,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.BigMomPirates, TypeTags.Homies ],
    cost: 2,
    effectText: `[Activate: Main] You may rest this Stage and add 1 card from the top or bottom of your Life cards to your hand: Add up to 1 of your Characters with a cost of 3 to the top of the owner's Life cards face-up.`,
  },
];