import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.ST09,
    setNumber: 1,
    cardName: 'Yamato',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.LEADER,
    artists: [ 'NIJIMAARC' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [Opponent's Turn] If you have 2 or less Life cards, this Leader gains +1000 power.`,
    life: 5,
  },{
    setId: SetId.ST09,
    setNumber: 2,
    cardName: 'Uzuki Tempura',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SLASH,
    triggerText: `[Trigger] Rest up to 1 of your opponent's Characters with a cost of 2 or less and add this card to your hand.`,
    counter: 1000,
  },{
    setId: SetId.ST09,
    setNumber: 3,
    cardName: 'Ulti',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Sunohara' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST09,
    setNumber: 4,
    cardName: 'Kaido',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Ryuda' ],
    blockIcon: 1,
    types: [ TypeTags.AnimalKingdomPirates ],
    cost: 4,
    power: 5000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[DON!! x1] If you have 2 or less Life cards, this Character cannot be K.O.'d in battle.`,
    counter: 1000,
  },{
    setId: SetId.ST09,
    setNumber: 5,
    cardName: 'Kouzuki Oden',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Makitoshi' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 7,
    power: 7000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] This Character gains [Double Attack].
    (This card deals 2 damage.)
    [On K.O.] You may trash 2 cards from your hand: Add up to 1 card from the top of your deck to the top of your Life cards.`,
  },{
    setId: SetId.ST09,
    setNumber: 6,
    cardName: 'Kouzuki Momonosuke',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.KouzukiClan ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.ST09,
    setNumber: 7,
    cardName: 'Shinobu',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Sunohara' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 3,
    power: 2000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Block] You may add 1 card from the top or bottom of your Life cards to your hand: This Character gains +4000 power during this battle.`,
  },{
    setId: SetId.ST09,
    setNumber: 8,
    cardName: 'Shimotsuki Ushimaru',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 5,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] You may add 1 card from the top or bottom of your Life cards to your hand: Play up to 1 yellow {Land of Wano} type Character card with a cost of 4 or less from your hand.`,
  },{
    setId: SetId.ST09,
    setNumber: 9,
    cardName: 'Fugetsu Omusubi',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    triggerText: `[Trigger] K.O. up to 1 of your opponent's Characters with a cost of 1 or less and add this card to your hand.`,
    counter: 1000,
  },{
    setId: SetId.ST09,
    setNumber: 10,
    cardName: 'Portgas.D.Ace',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.WhitebeardPirates ],
    cost: 6,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[Once Per Turn] If this Character would be K.O.'d, you may trash 1 card from the top or bottom of your Life cards instead.`,
  },{
    setId: SetId.ST09,
    setNumber: 11,
    cardName: 'Monkey.D.Luffy',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Misa Matoki' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano, TypeTags.StrawHatCrew ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST09,
    setNumber: 12,
    cardName: 'Yamato',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Saya Tsuruta' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 3,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[When Attacking] You may add 1 card from the top or bottom of your Life cards to your hand: This Character gains +2000 power until the start of your next turn.`,
    counter: 2000,
  },{
    setId: SetId.ST09,
    setNumber: 13,
    cardName: 'Yamato',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Moopic' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 5,
    power: 7000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.ST09,
    setNumber: 14,
    cardName: 'Narikabura Arrow',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 1,
    effectText: `[Counter] If you have 2 or less Life cards, give up to 1 of your opponent's Leader or Character cards -3000 power during this turn.`,
    triggerText: `[Trigger] You may trash 2 cards from your hand: Add up to 1 card from the top of your deck to the top of your Life cards.`,
  },{
    setId: SetId.ST09,
    setNumber: 15,
    cardName: 'Thunder Bagua',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.YELLOW ],
    rarity: CardRarity.COMMON,
    artists: [ 'Manga' ],
    blockIcon: 1,
    types: [ TypeTags.LandOfWano ],
    cost: 2,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, if you have 2 or less Life cards, add up to 1 of your opponent's Characters with a cost of 3 or less to the top or bottom of the owner's Life cards face-up.`,
    triggerText: `[Trigger] Draw 1 card.`,
  },
];
