import {
  DbCard,
  SetId,
  CardType,
  CardColor,
  CardRarity,
  CardAttribute,
  TypeTags
} from "setdb/constants";

export const cardList: DbCard[] = [
  {
    setId: SetId.ST12,
    setNumber: 1,
    cardName: 'Roronoa Zoro & Sanji',
    cardType: CardType.LEADER,
    cardColors: [ CardColor.GREEN, CardColor.BLUE ],
    rarity: CardRarity.LEADER,
    artists: [ 'S-KINOKO' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    power: 5000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] [Once Per Turn] You may return 1 of your Characters with a cost of 2 or more to the owner's hand: Set up to 1 of your Characters with 7000 power or less as active.`,
    life: 4,
  },{
    setId: SetId.ST12,
    setNumber: 2,
    cardName: 'Kuina',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'SOWSOW' ],
    blockIcon: 2,
    types: [ TypeTags.FrostMoonVillage ],
    cost: 3,
    power: 2000,
    attribute: CardAttribute.SLASH,
    effectText: `[Activate: Main] You may rest this Character: Rest up to 1 of your opponent's Characters with a cost of 4 or less.`,
    triggerText: `[Trigger] Play this card.`,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 3,
    cardName: 'Dracule Mihawk',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Hashimoto Q' ],
    blockIcon: 2,
    types: [ TypeTags.TheSevenWarlordsOfTheSea, TypeTags.MuggyKingdom ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SLASH,
    effectText: `[On Play] If you have 2 or less Characters, play up to 1 {Muggy Kingdom} type or <Slash> attribute Character card with a cost of 4 or less other than [Dracule Mihawk] from your hand rested.`,
    counter: 2000,
  },{
    setId: SetId.ST12,
    setNumber: 4,
    cardName: 'Humandrill',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'S-KINOKO' ],
    blockIcon: 2,
    types: [ TypeTags.Animal, TypeTags.MuggyKingdom ],
    cost: 3,
    power: 5000,
    attribute: CardAttribute.WISDOM,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 5,
    cardName: 'Perona',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Hatori Kyoka' ],
    blockIcon: 2,
    types: [ TypeTags.MuggyKingdom, TypeTags.ThrillerBarkPirates ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SPECIAL,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 6,
    cardName: 'Yosaku & Johnny',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Akihiro MIYANO' ],
    blockIcon: 2,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] Choose one:
    • Rest up to 1 of your opponent's Characters with a cost of 2 or less.
    • K.O. up to 1 of your opponent's rested Characters with a cost of 2 or less.`,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 7,
    cardName: 'Rika',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'SOWSOW' ],
    blockIcon: 2,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 0,
    attribute: CardAttribute.WISDOM,
    effectText: `[On Play] ➁ (You may rest the specified number of DON!! cards in your cost area.): If your opponent has 3 or more Life cards, set up to 1 of your <Slash> attribute Characters with a cost of 4 or less as active.`,
    counter: 2000,
  },{
    setId: SetId.ST12,
    setNumber: 8,
    cardName: 'Roronoa Zoro',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'Anderson' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 4,
    power: 6000,
    attribute: CardAttribute.SLASH,
    effectText: `[DON!! x1] [When Attacking] Rest up to 1 of your opponent's Characters with a cost of 6 or less.`,
  },{
    setId: SetId.ST12,
    setNumber: 9,
    cardName: 'Elephant True Bluefin',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'KISUKE' ],
    blockIcon: 2,
    types: [ TypeTags.Animal ],
    cost: 1,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 10,
    cardName: 'Emporio.Ivankov',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.SUPER_RARE,
    artists: [ 'Denim2' ],
    blockIcon: 2,
    types: [ TypeTags.ImpelDown, TypeTags.RevolutionaryArmy ],
    cost: 3,
    power: 4000,
    attribute: CardAttribute.SPECIAL,
    effectText: `[On Play] Reveal 1 card from the top of your deck and play up to 1 Character card with a cost of 2. Then, place the rest at the top or bottom of your deck.
    [When Attacking] [Once Per Turn] Draw 1 card if you have 6 or less cards in your hand.`,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 11,
    cardName: 'Sanji',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Ryuda' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 2,
    power: 3000,
    attribute: CardAttribute.STRIKE,
    effectText: `[DON!! x1] [When Attacking] If you have 5 or less cards in your hand, this Character gains +2000 power until the start of your next turn.`,
  },{
    setId: SetId.ST12,
    setNumber: 12,
    cardName: 'Charlotte Pudding',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'otton' ],
    blockIcon: 2,
    types: [ TypeTags.BigMomPirates ],
    cost: 2,
    power: 2000,
    attribute: CardAttribute.WISDOM,
    effectText: `[Activate: Main] Return this Character to the owner's hand.`,
    counter: 2000,
  },{
    setId: SetId.ST12,
    setNumber: 13,
    cardName: 'Zeff',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'Studio Vigor Co.,Ltd' ],
    blockIcon: 2,
    types: [ TypeTags.EastBlue ],
    cost: 5,
    power: 5000,
    attribute: CardAttribute.STRIKE,
    effectText: `[On Play] Look at 3 cards from the top of your deck and place them at the top or bottom of the deck in any order.
    [When Attacking] Reveal 1 card from the top of your deck and play up to 1 Character card with a cost of 2 rested. Then, place the rest at the top or bottom of your deck.`,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 14,
    cardName: 'Duval',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'COGA' ],
    blockIcon: 2,
    types: [ TypeTags.FlyingFishPirates ],
    cost: 2,
    power: 1000,
    attribute: CardAttribute.STRIKE,
    effectText: `[Blocker] (After your opponent declares an attack, you may rest this card to make it the new target of the attack.)
    [On Play] Look at 3 cards from the top of your deck and place them at the top or bottom of the deck in any order.`,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 15,
    cardName: 'Patty & Carne',
    cardType: CardType.CHARACTER,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'SENNSU' ],
    blockIcon: 2,
    types: [ TypeTags.EastBlue ],
    cost: 2,
    power: 4000,
    attribute: CardAttribute.SLASH,
    counter: 1000,
  },{
    setId: SetId.ST12,
    setNumber: 16,
    cardName: 'Lion Strike',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.GREEN ],
    rarity: CardRarity.COMMON,
    artists: [ 'tatsuya' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 2,
    effectText: `[Main]/[Counter] Rest up to 1 of your opponent's Leader or Character cards with a cost of 4 or less.`,
    triggerText: `[Trigger] Activate this card's [Main] effect.`,
  },{
    setId: SetId.ST12,
    setNumber: 17,
    cardName: 'Plastic Surgery Shot',
    cardType: CardType.EVENT,
    cardColors: [ CardColor.BLUE ],
    rarity: CardRarity.COMMON,
    artists: [ 'akagi' ],
    blockIcon: 2,
    types: [ TypeTags.StrawHatCrew ],
    cost: 1,
    effectText: `[Counter] Up to 1 of your Leader or Character cards gains +2000 power during this battle. Then, reveal 1 card from the top of your deck, play up to 1 Character card with a cost of 2, and place the rest at the top or bottom of your deck.`,
  },
];